/*===========================================================================+
|  Function : Control                                                        |
|  Task     : Machine Control Utilities header file                          |
|----------------------------------------------------------------------------|
|  Compile  : gcc                                                     		|
|  Link     : gcc                                                     		|
|  Call     :                                                                |
|----------------------------------------------------------------------------|
|  Author   :                                                       		|
|  Version  : V1.00                                                          |
|  Creation :                                                      			|
|  Revision :                                                      			|
+===========================================================================*/

#ifndef     D_DBID
#define     D_DBID

/*==========================================================================+
|           Global database ID                                              |
+==========================================================================*/
/*==========================================================================+
|           taski32 ID		                                                |
+==========================================================================*/
#define		TECH_LUB_GENER_ACTTIME											    "TECH_LUB_GENER_ACTTIME"									      
#define		TECH_LUB_GENER_AUTOLUBACOUNT                                        "TECH_LUB_GENER_AUTOLUBACOUNT"                                 
#define		TECH_MDH_GENER_RAILINGTON                                           "TECH_MDH_GENER_RAILINGTON"                                        
#define		TECH_MDH_GENER_RAILINGDISTANCE                                      "TECH_MDH_GENER_RAILINGDISTANCE"                                   
#define		TECH_MDH_GENER_ADJUSTCOUNTER                                        "TECH_MDH_GENER_ADJUSTCOUNTER"                                 
#define		TECH_MLD_GENER_CLAMPFORCESET                                        "TECH_MLD_GENER_CLAMPFORCESET"                                 
#define		TECH_GENER_SETSHOTCOUNT                                             "TECH_GENER_SETSHOTCOUNT"                                      
#define		TECH_GENER_CYCLEDELAY                                               "TECH_GENER_CYCLEDELAY"                                        
#define		TECH_EJT_GENER_POSIEJECTTRAVEL                                      "TECH_EJT_GENER_POSIEJECTTRAVEL"                               
#define		TECH_MLD_GENER_TIMECOOLER                                           "TECH_MLD_GENER_TIMECOOLER"                                    
#define		TECH_IJU_GENER_BACKWARDMODE                                         "TECH_IJU_GENER_BACKWARDMODE"                                 
#define		TECH_ALM_GENER_AUTOALARMRESET                                       "TECH_ALM_GENER_AUTOALARMRESET"                                
#define		TECH_GENER_CYCLEDEFAULTMAX                                          "TECH_GENER_CYCLEDEFAULTMAX"                                   
#define		TECH_MLD_GENER_CLOSEPROTECTDEFAULTMAX                               "TECH_MLD_GENER_CLOSEPROTECTDEFAULTMAX"                        
#define		TECH_MLD_GENER_CLOSEHIGHDEFAULTMAX                                  "TECH_MLD_GENER_CLOSEHIGHDEFAULTMAX"                           
#define		TECH_RCV_GENER_CHARGEDEFAULTMAX                                     "TECH_RCV_GENER_CHARGEDEFAULTMAX"                             
#define		TECH_PSTDECOM_GENER_SUCKBACKDEFAULTMAX                              "TECH_PSTDECOM_GENER_SUCKBACKDEFAULTMAX"                       
#define		TECH_IJU_GENER_NOZZLEDEFAULTMAX                                     "TECH_IJU_GENER_NOZZLEDEFAULTMAX"                              
#define		TECH_EJT_GENER_DEFAULTMAX                                           "TECH_EJT_GENER_DEFAULTMAX"
#define		TECH_TEMP_PROF_NSETTING_                                            "TECH_TEMP_PROF_NSETTING_"                                     
#define		TECH_TEMP_PROF_NRAMP_                                               "TECH_TEMP_PROF_NRAMP_"                                       
#define		TECH_TEMP_PROFLMT_NMAX_                                             "TECH_TEMP_PROFLMT_NMAX_"                                      
#define		TECH_TEMP_PROFLMT_NMIN_                                             "TECH_TEMP_PROFLMT_NMIN_"                                      
#define		TECH_TEMP_CONFIG_WKP_                                               "TECH_TEMP_CONFIG_WKP_"                                        
#define		TECH_TEMP_CONFIG_WKI_                                               "TECH_TEMP_CONFIG_WKI_"                                        
#define		TECH_TEMP_CONFIG_WKD_                                               "TECH_TEMP_CONFIG_WKD_"                                        
#define		TECH_TEMP_CONFIG_WDT_                                               "TECH_TEMP_CONFIG_WDT_"                                        
#define		TECH_TEMP_CONFIG_WTD_                                               "TECH_TEMP_CONFIG_WTD_"                                        
#define		TECH_TEMP_INTERFACE_WSTATUS_                                        "TECH_TEMP_INTERFACE_WSTATUS_"                                 
#define		TECH_TEMP_INTERFACE_NCURRENT_                                       "TECH_TEMP_INTERFACE_NCURRENT_"                                
#define		TECH_TEMP_INTERFACE_NACCCURRENT_                                    "TECH_TEMP_INTERFACE_NACCCURRENT_"                             
#define		TECH_TEMP_INTERFACE_NACCLAST_                                       "TECH_TEMP_INTERFACE_NACCLAST_"                                
#define		TECH_TEMP_INTERFACE_NSUM_                                           "TECH_TEMP_INTERFACE_NSUM_"                                    
#define		TECH_TEMP_INTERFACE_NDE_                                            "TECH_TEMP_INTERFACE_NDE_"                                     
#define		TECH_TEMP_INTERFACE_NDDE_                                           "TECH_TEMP_INTERFACE_NDDE_"                                    
#define		TECH_TEMP_INTERFACE_WKPOUT_                                         "TECH_TEMP_INTERFACE_WKPOUT_"                                  
#define		TECH_TEMP_INTERFACE_WKIOUT_                                         "TECH_TEMP_INTERFACE_WKIOUT_"                                  
#define		TECH_TEMP_INTERFACE_WKDOUT_                                         "TECH_TEMP_INTERFACE_WKDOUT_"                                  
#define		TECH_TEMP_INTERFACE_NMAXUPDDE_                                      "TECH_TEMP_INTERFACE_NMAXUPDDE_"                               
#define		TECH_TEMP_INTERFACE_NMAXDNDDE_                                      "TECH_TEMP_INTERFACE_NMAXDNDDE_"                               
#define		TECH_GENER_MONITOR_CYCLETIMEPCT                                     "TECH_GENER_MONITOR_CYCLETIMEPCT"                              
#define		TECH_MLD_GENER_MONITOR_CLAMPCLOSEPCT                                "TECH_MLD_GENER_MONITOR_CLAMPCLOSEPCT"                         
#define		TECH_MLD_GENER_MONITOR_CLAMPOPENPCT                                 "TECH_MLD_GENER_MONITOR_CLAMPOPENPCT"                          
#define		TECH_INJ_GENER_MONITOR_INJECTPCT                                    "TECH_INJ_GENER_MONITOR_INJECTPCT"                             
#define		TECH_RCV_GENER_MONITOR_CHARGEPCT                                    "TECH_RCV_GENER_MONITOR_CHARGEPCT"                             
#define		TECH_PSTDECOM_GENER_MONITOR_SUCKBACKPCT                             "TECH_PSTDECOM_GENER_MONITOR_SUCKBACKPCT"                      
#define		TECH_EJT_GENER_MONITOR_EJECTPCT                                     "TECH_EJT_GENER_MONITOR_EJECTPCT"                              
#define		TECH_MLD_GENER_MONITOR_CLAMPOPENENDPCT                              "TECH_MLD_GENER_MONITOR_CLAMPOPENENDPCT"                       
#define		TECH_TRANSITION_GENER_MONITOR_PRESTURNTOHOLDPCT                     "TECH_TRANSITION_GENER_MONITOR_PRESTURNTOHOLDPCT"              
#define		TECH_TRANSITION_GENER_MONITOR_TURNTOHOLDPCT                         "TECH_TRANSITION_GENER_MONITOR_TURNTOHOLDPCT"                  
#define		TECH_TRANSITION_GENER_MONITOR_POSITURNTOHOLDPCT                     "TECH_TRANSITION_GENER_MONITOR_POSITURNTOHOLDPCT"              
#define		TECH_TRANSITION_GENER_MONITOR_POSIINJECTSTARTPCT                    "TECH_TRANSITION_GENER_MONITOR_POSIINJECTSTARTPCT"             
#define		TECH_CUSHION_INTERFACE_MONITOR_POSIINJECTHOLDEND                    "TECH_CUSHION_INTERFACE_MONITOR_POSIINJECTHOLDEND"             
#define		TECH_INTERFACE_SHOTCOUNT                                           "TECH_INTERFACE_SHOTCOUNT"                                    
#define		TECH_ALM_GENER_AUTOALARMUNIT                                        "TECH_ALM_GENER_AUTOALARMUNIT"                                 
#define		TECH_TRANSITION_GENER_MONITOR_POSIINJECTHOLDENDPCT                  "TECH_TRANSITION_GENER_MONITOR_POSIINJECTHOLDENDPCT"          
#define		TECH_GENER_MONITOR_CYCLETIMEVAL                                     "TECH_GENER_MONITOR_CYCLETIMEVAL"                              
#define		TECH_MLD_GENER_MONITOR_CLAMPCLOSEVAL                                "TECH_MLD_GENER_MONITOR_CLAMPCLOSEVAL"                         
#define		TECH_MLD_GENER_MONITOR_CLAMPOPENVAL                                 "TECH_MLD_GENER_MONITOR_CLAMPOPENVAL"                          
#define		TECH_INJ_GENER_MONITOR_INJECTVAL                                    "TECH_INJ_GENER_MONITOR_INJECTVAL"                             
#define		TECH_RCV_GENER_MONITOR_CHARGEVAL                                    "TECH_RCV_GENER_MONITOR_CHARGEVAL"                             
#define		TECH_PSTDECOM_GENER_MONITOR_SUCKBACKVAL                             "TECH_PSTDECOM_GENER_MONITOR_SUCKBACKVAL"                      
#define		TECH_EJT_GENER_MONITOR_EJECTVAL                                     "TECH_EJT_GENER_MONITOR_EJECTVAL"                              
#define		TECH_MLD_GENER_MONITOR_CLAMPOPENENDVAL                              "TECH_MLD_GENER_MONITOR_CLAMPOPENENDVAL"                       
#define		TECH_TRANSITION_GENER_MONITOR_PRESTURNTOHOLDVAL                     "TECH_TRANSITION_GENER_MONITOR_PRESTURNTOHOLDVAL"              
#define		TECH_TRANSITION_GENER_MONITOR_TURNTOHOLDVAL                         "TECH_TRANSITION_GENER_MONITOR_TURNTOHOLDVAL"                  
#define		TECH_TRANSITION_GENER_MONITOR_POSITURNTOHOLDVAL                     "TECH_TRANSITION_GENER_MONITOR_POSITURNTOHOLDVAL"              
#define		TECH_TRANSITION_GENER_MONITOR_POSIINJECTHOLDENDVAL                  "TECH_TRANSITION_GENER_MONITOR_POSIINJECTHOLDENDVAL"           
#define		TECH_TRANSITION_GENER_MONITOR_POSIINJECTSTARTVAL                    "TECH_TRANSITION_GENER_MONITOR_POSIINJECTSTARTVAL"             
#define		TECH_INTERFACE_OP_MODE                                              "TECH_INTERFACE_OP_MODE"                                       
#define		TECH_INTERFACE_OP_STEP                                              "TECH_INTERFACE_OP_STEP"       
#define		TECH_INTERFACE_OP_STEP2                                              "TECH_INTERFACE_OP_STEP2"                                 
#define		TECH_INTERFACE_MOTOR_STATUS                                         "TECH_INTERFACE_MOTOR_STATUS"                                  
#define		TECH_TEMP_INTERFACE_HEATER_STATUS                                   "TECH_TEMP_INTERFACE_HEATER_STATUS"                            
#define		TECH_INTERFACE_ACTION_TIME                                          "TECH_INTERFACE_ACTION_TIME"                                   
#define		TECH_INTERFACE_CYCLE_TIME                                           "TECH_INTERFACE_CYCLE_TIME"                                    
#define		TECH_ALM_GENER_ALARMSTATUS                                          "TECH_ALM_GENER_ALARMSTATUS"                                   
#define		TECH_INTERFACE_INOPERATION                                          "TECH_INTERFACE_INOPERATION"                                   
#define		TECH_INTERFACE_INPUT_												"TECH_INTERFACE_INPUT_%d"                                      
#define		TECH_INTERFACE_OUTPUT_                                              "TECH_INTERFACE_OUTPUT_%d"                                     
#define		MLD_TRACE_VELOCITYSETPOINT_POSNRECORDINGDATA						"MLD_TRACE_VELOCITYSETPOINT_POSNRECORDINGDATA"			    			//60310002
#define		MLD_TRACE_ACTUALVELOCITY_POSNRECORDINGDATA							"MLD_TRACE_ACTUALVELOCITY_POSNRECORDINGDATA"				    		//60300002
#define		MLD_TRACE_ACTUALFORCE_POSNRECORDINGDATA								"MLD_TRACE_ACTUALFORCE_POSNRECORDINGDATA"								//60320002
#define		MLD_TRACE_FORCELIMIT_POSNRECORDINGDATA								"MLD_TRACE_FORCELIMIT_POSNRECORDINGDATA"					    		//60330002
#define		INJ_TRACE_ACTUALHOLDPRESSURE_TMRECORDINGDATA						"INJ_TRACE_ACTUALHOLDPRESSURE_TMRECORDINGDATA"			    			//50350002
#define		INJ_TRACE_ACTUALINJPRESSURE_POSNRECORDINGDATA						"INJ_TRACE_ACTUALINJPRESSURE_POSNRECORDINGDATA"			    		//50330002
#define		INJ_TRACE_ACTUALINJVELOCITY_POSNRECORDINGDATA						"INJ_TRACE_ACTUALINJVELOCITY_POSNRECORDINGDATA"			    		//50310002
#define		INJ_TRACE_ACTUALTRANSITIONPOSITION_TMRECORDINGDATA					"INJ_TRACE_ACTUALTRANSITIONPOSITION_TMRECORDINGDATA"		    		//50380002
#define		INJ_TRACE_ACTUALTRANSITIONPRESSURE_TMRECORDINGDATA					"INJ_TRACE_ACTUALTRANSITIONPRESSURE_TMRECORDINGDATA"		    		//50360002
#define		INJ_TRACE_ACTUALTRANSITIONVELOCITY_TMRECORDINGDATA					"INJ_TRACE_ACTUALTRANSITIONVELOCITY_TMRECORDINGDATA"		    		//50370002
#define		INJ_TRACE_HOLDPRESSURESETPOINT_TMRECORDINGDATA						"INJ_TRACE_HOLDPRESSURESETPOINT_TMRECORDINGDATA"			    		//50340002
#define		INJ_TRACE_INJPRESSURELIMITSETPOINT_POSNRECORDINGDATA				"INJ_TRACE_INJPRESSURELIMITSETPOINT_POSNRECORDINGDATA"	    			//50320002
#define		INJ_TRACE_INTERPOLATEDVELOCITYSETPOINT_POSNRECORDINGDATA			"INJ_TRACE_INTERPOLATEDVELOCITYSETPOINT_POSNRECORDINGDATA"   			//50300002
#define		RCV_TRACE_ACTUALPRESSURE_POSNRECORDINGDATA							"RCV_TRACE_ACTUALPRESSURE_POSNRECORDINGDATA"				    		//30320002
#define		RCV_TRACE_ACTUALSPEED_POSNRECORDINGDATA								"RCV_TRACE_ACTUALSPEED_POSNRECORDINGDATA"								//30300002
#define		RCV_TRACE_PRESSURESETPOINT_POSNRECORDINGDATA						"RCV_TRACE_PRESSURESETPOINT_POSNRECORDINGDATA"			    			//30330002
#define		RCV_TRACE_SPEEDSETPOINT_POSNRECORDINGDATA							"RCV_TRACE_SPEEDSETPOINT_POSNRECORDINGDATA"				    		//30310002

#define		TECH_LUB_INTERFACE_RESPONSEIOCOUNT    								"TECH_LUB_INTERFACE_RESPONSEIOCOUNT"    
#define		TECH_LUB_GENER_DELAYTIME              								"TECH_LUB_GENER_DELAYTIME"              
#define		TECH_LUB_GENER_ACTTIME2               								"TECH_LUB_GENER_ACTTIME2"               
#define		TECH_LUB_GENER_AUTOLUBACOUNT2         								"TECH_LUB_GENER_AUTOLUBACOUNT2"         
#define		TECH_LUB_GENER_REQUESTIOCOUNT        								"TECH_LUB_GENER_REQUESTIOCOUNT" 
#define		TECH_LUB_GENER_REQUESTIOCOUNT2        								"TECH_LUB_GENER_REQUESTIOCOUNT2"        
#define		TECH_LUB_INTERFACE_RESPONSEIOCOUNT2   								"TECH_LUB_INTERFACE_RESPONSEIOCOUNT2"   
#define		TECH_LUB_GENER_DELAYTIME2             								"TECH_LUB_GENER_DELAYTIME2"             
#define		TECH_MDH_GENER_RAILINGTIME            								"TECH_MDH_GENER_RAILINGTIME"           
#define		TECH_MLD_GENER_CLOSELINK              								"TECH_MLD_GENER_CLOSELINK"              
#define		TECH_MLD_GENER_OPENLINK               								"TECH_MLD_GENER_OPENLINK"               
#define		TECH_EJT_GENER_POSNOPENLINK           								"TECH_EJT_GENER_POSNOPENLINK"           
#define		EJT_GENER_CNNOSTROKES                 								"EJT_GENER_CNNOSTROKES"                 
#define		TECH_EJT_GENER_MODE                   								"TECH_EJT_GENER_MODE"              
#define		TECH_IJU_GENER_BACKWARDTTIME          								"TECH_IJU_GENER_BACKWARDTTIME"          
#define		TECH_IJU_GENER_FORWARDDELAYCLAMPUP    								"TECH_IJU_GENER_FORWARDDELAYCLAMPUP"    
#define		TECH_IJU_GENER_BACKWARDDELAYBRAKEOFF  								"TECH_IJU_GENER_BACKWARDDELAYBRAKEOFF"
#define		TECH_IJU_GENER_BACKWARDDELAYON  									"TECH_IJU_GENER_BACKWARDDELAYON"
#define		TECH_PSTDECOM_GENER_SUCKBACKMODE      								"TECH_PSTDECOM_GENER_SUCKBACKMODE"      
#define		TECH_COREA_GENER_FUNCTION             								"TECH_COREA_GENER_FUNCTION"             
#define		TECH_COREA_GENER_MODE                 								"TECH_COREA_GENER_MODE"                 
#define		TECH_COREA_GENER_INPOINT              								"TECH_COREA_GENER_INPOINT"              
#define		TECH_COREA_GENER_INDELAY              								"TECH_COREA_GENER_INDELAY"              
#define		TECH_COREA_GENER_INACTTIME            								"TECH_COREA_GENER_INACTTIME"            
#define		TECH_COREA_GENER_INACTPOSN            								"TECH_COREA_GENER_INACTPOSN"            
#define		TECH_COREA_GENER_INCOUNT              								"TECH_COREA_GENER_INCOUNT"              
#define		TECH_COREA_GENER_OUTPOINT             								"TECH_COREA_GENER_OUTPOINT"             
#define		TECH_COREA_GENER_OUTDELAY             								"TECH_COREA_GENER_OUTDELAY"             
#define		TECH_COREA_GENER_OUTACTTIME           								"TECH_COREA_GENER_OUTACTTIME"           
#define		TECH_COREA_GENER_OUTACTPOSN           								"TECH_COREA_GENER_OUTACTPOSN"           
#define		TECH_COREA_GENER_OUTCOUNT             								"TECH_COREA_GENER_OUTCOUNT"             
#define		TECH_COREB_GENER_FUNCTION             								"TECH_COREB_GENER_FUNCTION"             
#define		TECH_COREB_GENER_MODE                 								"TECH_COREB_GENER_MODE"                 
#define		TECH_COREB_GENER_INPOINT              								"TECH_COREB_GENER_INPOINT"              
#define		TECH_COREB_GENER_INDELAY              								"TECH_COREB_GENER_INDELAY"              
#define		TECH_COREB_GENER_INACTTIME            								"TECH_COREB_GENER_INACTTIME"            
#define		TECH_COREB_GENER_INACTPOSN            								"TECH_COREB_GENER_INACTPOSN"            
#define		TECH_COREB_GENER_INCOUNT              								"TECH_COREB_GENER_INCOUNT"              
#define		TECH_COREB_GENER_OUTPOINT             								"TECH_COREB_GENER_OUTPOINT"             
#define		TECH_COREB_GENER_OUTDELAY             								"TECH_COREB_GENER_OUTDELAY"             
#define		TECH_COREB_GENER_OUTACTTIME           								"TECH_COREB_GENER_OUTACTTIME"           
#define		TECH_COREB_GENER_OUTACTPOSN           								"TECH_COREB_GENER_OUTACTPOSN"           
#define		TECH_COREB_GENER_OUTCOUNT             								"TECH_COREB_GENER_OUTCOUNT"             
#define		TECH_COREC_GENER_FUNCTION             								"TECH_COREC_GENER_FUNCTION"             
#define		TECH_COREC_GENER_MODE                 								"TECH_COREC_GENER_MODE"                 
#define		TECH_COREC_GENER_INPOINT              								"TECH_COREC_GENER_INPOINT"              
#define		TECH_COREC_GENER_INDELAY              								"TECH_COREC_GENER_INDELAY"              
#define		TECH_COREC_GENER_INACTTIME            								"TECH_COREC_GENER_INACTTIME"            
#define		TECH_COREC_GENER_INACTPOSN            								"TECH_COREC_GENER_INACTPOSN"            
#define		TECH_COREC_GENER_INCOUNT              								"TECH_COREC_GENER_INCOUNT"              
#define		TECH_COREC_GENER_OUTPOINT             								"TECH_COREC_GENER_OUTPOINT"             
#define		TECH_COREC_GENER_OUTDELAY             								"TECH_COREC_GENER_OUTDELAY"             
#define		TECH_COREC_GENER_OUTACTTIME           								"TECH_COREC_GENER_OUTACTTIME"           
#define		TECH_COREC_GENER_OUTACTPOSN           								"TECH_COREC_GENER_OUTACTPOSN"           
#define		TECH_COREC_GENER_OUTCOUNT             								"TECH_COREC_GENER_OUTCOUNT"             
#define		TECH_CORED_GENER_FUNCTION             								"TECH_CORED_GENER_FUNCTION"             
#define		TECH_CORED_GENER_MODE                 								"TECH_CORED_GENER_MODE"                 
#define		TECH_CORED_GENER_INPOINT              								"TECH_CORED_GENER_INPOINT"              
#define		TECH_CORED_GENER_INDELAY              								"TECH_CORED_GENER_INDELAY"              
#define		TECH_CORED_GENER_INACTTIME            								"TECH_CORED_GENER_INACTTIME"            
#define		TECH_CORED_GENER_INACTPOSN            								"TECH_CORED_GENER_INACTPOSN"            
#define		TECH_CORED_GENER_INCOUNT              								"TECH_CORED_GENER_INCOUNT"              
#define		TECH_CORED_GENER_OUTPOINT             								"TECH_CORED_GENER_OUTPOINT"             
#define		TECH_CORED_GENER_OUTDELAY             								"TECH_CORED_GENER_OUTDELAY"             
#define		TECH_CORED_GENER_OUTACTTIME           								"TECH_CORED_GENER_OUTACTTIME"           
#define		TECH_CORED_GENER_OUTACTPOSN           								"TECH_CORED_GENER_OUTACTPOSN"           
#define		TECH_CORED_GENER_OUTCOUNT             								"TECH_CORED_GENER_OUTCOUNT"             
#define		TECH_BLASTA_GENER_ACTTIME             								"TECH_BLASTA_GENER_ACTTIME"             
#define		TECH_BLASTA_GENER_DELAY               								"TECH_BLASTA_GENER_DELAY"               
#define		TECH_BLASTA_GENER_ACTPOSN             								"TECH_BLASTA_GENER_ACTPOSN"             
#define		TECH_BLASTB_GENER_ACTTIME             								"TECH_BLASTB_GENER_ACTTIME"             
#define		TECH_BLASTB_GENER_DELAY               								"TECH_BLASTB_GENER_DELAY"               
#define		TECH_BLASTB_GENER_ACTPOSN             								"TECH_BLASTB_GENER_ACTPOSN"             
#define		TECH_BLASTC_GENER_ACTTIME             								"TECH_BLASTC_GENER_ACTTIME"             
#define		TECH_BLASTC_GENER_DELAY               								"TECH_BLASTC_GENER_DELAY"               
#define		TECH_BLASTC_GENER_ACTPOSN             								"TECH_BLASTC_GENER_ACTPOSN"             
#define		TECH_BLASTD_GENER_ACTTIME             								"TECH_BLASTD_GENER_ACTTIME"             
#define		TECH_BLASTD_GENER_DELAY               								"TECH_BLASTD_GENER_DELAY"               
#define		TECH_BLASTD_GENER_ACTPOSN             								"TECH_BLASTD_GENER_ACTPOSN"             
#define		TECH_RCV_GENER_PURGECOUNT             								"TECH_RCV_GENER_PURGECOUNT"  
#define		TECH_IJU_GENER_FORWARDDELAYBRAKEON									"TECH_IJU_GENER_FORWARDDELAYBRAKEON"
#define		TECH_EJT_GENER_POSNWORKAREA											"TECH_EJT_GENER_POSNWORKAREA"
#define		MLD_GENER_POSNMOLDOPENPOSITION										"MLD_GENER_POSNMOLDOPENPOSITION"
#define		TECH_CORE_GENER_POSNWORKAREA										"TECH_CORE_GENER_POSNWORKAREA"
#define		TECH_TEMP_24HOUR_FLAGHEATER											"TECH_TEMP_24HOUR_FLAGHEATER"				//24小時定時加溫	
#define		TECH_MLD_GENER_OPEN_TOTALSETZERO									"TECH_MLD_GENER_OPEN_TOTALSETZERO"			//總數到				0x0001開模總數歸零 0x0002裝模總數歸零
#define		TECH_EJT_GENER_PHOTOSENSOR											"TECH_EJT_GENER_PHOTOSENSOR"				//電眼檢測
#define		TECH_GENER_FLAGPOWERDOOR											"TECH_GENER_FLAGPOWERDOOR"					//自動安全門
#define		TECH_GENER_FLAGROTBOT												"TECH_GENER_FLAGROTBOT"						//機械手選用
#define		TECH_LUB_INTERFACE_RESPONSEIOSHOTCOUNT								"TECH_LUB_INTERFACE_RESPONSEIOSHOTCOUNT"
#define		TECH_LUB_INTERFACE_RESPONSEIOSHOTCOUNT2								"TECH_LUB_INTERFACE_RESPONSEIOSHOTCOUNT2"
#define		TECH_TEMP_24HOUR_FLAGHEATERON                						"TECH_TEMP_24HOUR%d_FLAGHEATERON"      
#define		TECH_TEMP_24HOUR_FLAGHEATERON_HOUR                  				"TECH_TEMP_24HOUR%d_FLAGHEATERON_HOUR" 
#define		TECH_TEMP_24HOUR_FLAGHEATERON_MIN                   				"TECH_TEMP_24HOUR%d_FLAGHEATERON_MIN"  
#define		TECH_TEMP_24HOUR_FLAGHEATEROFF                      				"TECH_TEMP_24HOUR%d_FLAGHEATEROFF"     
#define		TECH_TEMP_24HOUR_FLAGHEATEROFF_HOUR                 				"TECH_TEMP_24HOUR%d_FLAGHEATEROFF_HOUR"
#define		TECH_TEMP_24HOUR_FLAGHEATEROFF_MIN                  				"TECH_TEMP_24HOUR%d_FLAGHEATEROFF_MIN" 
#define		TECH_GENER_PACKSHOTCOUNT											"TECH_GENER_PACKSHOTCOUNT"
#define		TECH_INTERFACE_PACKSHOTCOUNT										"TECH_INTERFACE_PACKSHOTCOUNT"
#define		TECH_GENER_PRODUCTPERCOUNT											"TECH_GENER_PRODUCTPERCOUNT"
#define		EJT_GENER_TMDELAYTIMEATFWDPOSITION									"EJT_GENER_TMDELAYTIMEATFWDPOSITION"				//ejector forword delay time
#define		EJT_GENER_TMDELAYTIMEATSTROKEPOSITION								"EJT_GENER_TMDELAYTIMEATSTROKEPOSITION"				//ejector backword delay time
                                                                				
#define		TECH_INTERFACE_MONITOR_CYCLETIME           							"TECH_INTERFACE_MONITOR_CYCLETIME"           			
#define		TECH_MLD_INTERFACE_MONITOR_CLAMPCLOSE               				"TECH_MLD_INTERFACE_MONITOR_CLAMPCLOSE"               
#define		TECH_MLD_INTERFACE_MONITOR_CLAMPOPEN                				"TECH_MLD_INTERFACE_MONITOR_CLAMPOPEN"                
#define		TECH_INJ_INTERFACE_MONITOR_INJECT                   				"TECH_INJ_INTERFACE_MONITOR_INJECT"                   
#define		TECH_RCV_INTERFACE_MONITOR_CHARGE                   				"TECH_RCV_INTERFACE_MONITOR_CHARGE"                   
#define		TECH_PSTDECOM_INTERFACE_MONITOR_SUCKBACK            				"TECH_PSTDECOM_INTERFACE_MONITOR_SUCKBACK"            
#define		TECH_EJT_INTERFACE_MONITOR_EJECT                    				"TECH_EJT_INTERFACE_MONITOR_EJECT"                    
#define		TECH_MLD_INTERFACE_MONITOR_CLAMPOPENEND             				"TECH_MLD_INTERFACE_MONITOR_CLAMPOPENEND"             
#define		TECH_TRANSITION_INTERFACE_MONITOR_PRESTURNTOHOLD    				"TECH_TRANSITION_INTERFACE_MONITOR_PRESTURNTOHOLD"    
#define		TECH_TRANSITION_IINTERFACE_MONITOR_TURNTOHOLD       				"TECH_TRANSITION_IINTERFACE_MONITOR_TURNTOHOLD"       
#define		TECH_TRANSITION_IINTERFACE_MONITOR_POSITURNTOHOLD   				"TECH_TRANSITION_IINTERFACE_MONITOR_POSITURNTOHOLD"   
#define		TECH_INJ_INTERFACE_MONITOR_POSIINJECTSTART          				"TECH_INJ_INTERFACE_MONITOR_POSIINJECTSTART"          
#define		TECH_CUSHION_INTERFACE_MONITOR_POSIINJECTHOLDEND    				"TECH_CUSHION_INTERFACE_MONITOR_POSIINJECTHOLDEND"
#define		TECH_MDH_GENER_MOLDWIDTH											"TECH_MDH_GENER_MOLDWIDTH"	
#define		TECH_MDH_GENER_OBJWIDTH                                             "TECH_MDH_GENER_OBJWIDTH"    
#define		TECH_MDH_GENER_MODE                                                 "TECH_MDH_GENER_MODE"        
#define		TECH_MDH_INTERFACE_COUNTER                                          "TECH_MDH_INTERFACE_COUNTER" 
#define		TECH_MDH_GENER_CLAMPUP_SELECT										"TECH_MDH_GENER_CLAMPUP_SELECT"
/*==========================================================================+
|           tasksiem ID		                                                |
+==========================================================================*/
#define		EJT_INTERFACE_POSNACTUAL											"EJT_INTERFACE_POSNACTUAL"							//72000020,          
#define		EJT_INTERFACE_VELACTUAL		   				                        "EJT_INTERFACE_VELACTUAL"							//72000021,          
#define		RCV_INTERFACE_POSNACTUALSCREW				                        "RCV_INTERFACE_POSNACTUALSCREW"						//32000020,      
#define		RCV_INTERFACE_RPMACTUAL					 	                        "RCV_INTERFACE_RPMACTUAL"					 		//32000025,          
#define		RCV_INTERFACE_POSNACTUALSHOTSIZE			                        "RCV_INTERFACE_POSNACTUALSHOTSIZE"					//32000027,          
#define		RCV_INTERFACE_TORQACTUAL					                        "RCV_INTERFACE_TORQACTUAL"							//32000026,          
#define		RCV_INTERFACE_FORCEACTUAL					                        "RCV_INTERFACE_FORCEACTUAL"							//32000022,      
#define		RCV_INTERFACE_PRESMAX						                        "RCV_INTERFACE_PRESMAX"								//32000071,      
#define		RCV_INTERFACE_WORK							                        "RCV_INTERFACE_WORK"								//32000070,          
#define		INJ_INTERFACE_POSNACTUAL					                        "INJ_INTERFACE_POSNACTUAL"							//52000020,          
#define		INJ_INTERFACE_VELACTUAL						                        "INJ_INTERFACE_VELACTUAL"							//52000021,          
#define		INJ_INTERFACE_WORK							                        "INJ_INTERFACE_WORK"								//52000070,          
#define		INJ_INTERFACE_FORCEACTUAL					                        "INJ_INTERFACE_FORCEACTUAL"							//52000022,      
#define		INJ_INTERFACE_PRESMAXPRESSURE				                        "INJ_INTERFACE_PRESMAXPRESSURE"						//52000071,      
#define		INJ_INTERFACE_POSNTRANSITION				                        "INJ_INTERFACE_POSNTRANSITION"						//52000074,          
#define		INJ_INTERFACE_VELTRANSITION					                        "INJ_INTERFACE_VELTRANSITION"						//52000073,          
#define		INJ_INTERFACE_PRESTRANSITION				                        "INJ_INTERFACE_PRESTRANSITION"						//52000072,          
#define		INJ_INTERFACE_TMTRANSITION					                        "INJ_INTERFACE_TMTRANSITION"						//52000075,          
#define		INJ_INTERFACE_FLAGCUSHIONRESULT				                        "INJ_INTERFACE_FLAGCUSHIONRESULT"					//52000078,          
#define		INJ_INTERFACE_POSNCUSHION					                        "INJ_INTERFACE_POSNCUSHION"							//52000076,      
#define		INJ_INTERFACE_POSNCUSHIONCORRECTIONVALUE	                        "INJ_INTERFACE_POSNCUSHIONCORRECTIONVALUE"			//52000077,          
#define		MLD_INTERFACE_AXIS_POSITIONINGSTATE_POSNACTUAL                      "MLD_INTERFACE_AXIS_POSITIONINGSTATE_POSNACTUAL"	//62000023          
#define		MLD_INTERFACE_POSNACTUAL					                        "MLD_INTERFACE_POSNACTUAL"							//62000020           
#define		MLD_INTERFACE_VELACTUAL						                        "MLD_INTERFACE_VELACTUAL"							//62000021           
#define		MLD_INTERFACE_FORCEACTUALSENSOR				                        "MLD_INTERFACE_FORCEACTUALSENSOR"					//62000028           
#define		MLD_INTERFACE_FORCEACTUALDRIVE				                        "MLD_INTERFACE_FORCEACTUALDRIVE"					//62000022           
#define		MDH_INTERFACE_POSNSETPOINT					                        "MDH_INTERFACE_POSNSETPOINT"						//82000040           
#define		IJU_INTERFACE_POSNACTUAL					                        "IJU_INTERFACE_POSNACTUAL"							//12000020,          
#define		IJU_INTERFACE_VELACTUAL						                        "IJU_INTERFACE_VELACTUAL"							//12000021,          
#define		IJU_INTERFACE_FORCEACTUAL					                        "IJU_INTERFACE_FORCEACTUAL"							//12000022       
#define		MLD_INTERFACE_FLAGPOSITIONINGSTATE			                        "MLD_INTERFACE_FLAGPOSITIONINGSTATE"				// 開關模位置狀態    
#define		EJT_INTERFACE_FLAGPOSITIONINGSTATE			                        "EJT_INTERFACE_FLAGPOSITIONINGSTATE"				// 脫模位置狀態      
#define		INJ_INTERFACE_FLAGPOSITIONINGSTATE			                        "INJ_INTERFACE_FLAGPOSITIONINGSTATE"				// 射出位置狀態      
#define		IJU_INTERFACE_FLAGPOSITIONINGSTATE			                        "IJU_INTERFACE_FLAGPOSITIONINGSTATE"				// 座台位置狀態      
#define		RCV_INTERFACE_FLAGPOSITIONINGSTATE			                        "RCV_INTERFACE_FLAGPOSITIONINGSTATE"				// 儲料位置狀態      
#define		PSTDCP_INTERFACE_FLAGPOSITIONINGSTATE                               "PSTDCP_INTERFACE_FLAGPOSITIONINGSTATE"                             
#define		MLD_PROF_VELOCITYOPEN_CNNOPROFILEPOINTS		                        "MLD_PROF_VELOCITYOPEN_CNNOPROFILEPOINTS"		                     
#define		MLD_PROF_VELOCITYCLOSE_CNNOPROFILEPOINTS	                        "MLD_PROF_VELOCITYCLOSE_CNNOPROFILEPOINTS"	                         
#define		RCV_PROF_SPEED_CNNOPROFILEPOINTS			                        "RCV_PROF_SPEED_CNNOPROFILEPOINTS"			                         
#define		RCV_PROF_PRESSURE_CNNOPROFILEPOINTS			                        "RCV_PROF_PRESSURE_CNNOPROFILEPOINTS"			                     
#define		INJ_PROF_INJVELOCITY_CNNOPROFILEPOINTS		                        "INJ_PROF_INJVELOCITY_CNNOPROFILEPOINTS"		                     
#define		INJ_PROF_INJPRESSURELIMIT_CNNOPROFILEPOINTS	                        "INJ_PROF_INJPRESSURELIMIT_CNNOPROFILEPOINTS"	                     
#define		INJ_PROF_HOLDPRESSURE_CNNOPROFILEPOINTS		                        "INJ_PROF_HOLDPRESSURE_CNNOPROFILEPOINTS"		                     
#define		EJT_PROF_VELOCITYFWD_CNNOPROFILEPOINTS		                        "EJT_PROF_VELOCITYFWD_CNNOPROFILEPOINTS"		                     
#define		EJT_PROF_VELOCITYBWD_CNNOPROFILEPOINTS		                        "EJT_PROF_VELOCITYBWD_CNNOPROFILEPOINTS"		                     
#define		MLD_TRACE_ACTUALFORCE_POSNPRETRIGGERDELAY					        "MLD_TRACE_ACTUALFORCE_POSNPRETRIGGERDELAY"					     
#define		MLD_TRACE_ACTUALFORCE_FLAGRECORDINGMODE						        "MLD_TRACE_ACTUALFORCE_FLAGRECORDINGMODE"						     
#define		MLD_TRACE_ACTUALVELOCITY_POSNPRETRIGGERDELAY				        "MLD_TRACE_ACTUALVELOCITY_POSNPRETRIGGERDELAY"				         
#define		MLD_TRACE_ACTUALVELOCITY_FLAGRECORDINGMODE					        "MLD_TRACE_ACTUALVELOCITY_FLAGRECORDINGMODE"					     
#define		MLD_TRACE_FORCELIMIT_POSNPRETRIGGERDELAY					        "MLD_TRACE_FORCELIMIT_POSNPRETRIGGERDELAY"					         
#define		MLD_TRACE_FORCELIMIT_FLAGRECORDINGMODE						        "MLD_TRACE_FORCELIMIT_FLAGRECORDINGMODE"						     
#define		MLD_TRACE_VELOCITYSETPOINT_POSNPRETRIGGERDELAY				        "MLD_TRACE_VELOCITYSETPOINT_POSNPRETRIGGERDELAY"				     
#define		MLD_TRACE_VELOCITYSETPOINT_FLAGRECORDINGMODE				        "MLD_TRACE_VELOCITYSETPOINT_FLAGRECORDINGMODE"				         
#define		RCV_TRACE_ACTUALPRESSURE_POSNPRETRIGGERDELAY				        "RCV_TRACE_ACTUALPRESSURE_POSNPRETRIGGERDELAY"				         
#define		RCV_TRACE_ACTUALPRESSURE_FLAGRECORDINGMODE					        "RCV_TRACE_ACTUALPRESSURE_FLAGRECORDINGMODE"					     
#define		RCV_TRACE_ACTUALSPEED_POSNPRETRIGGERDELAY					        "RCV_TRACE_ACTUALSPEED_POSNPRETRIGGERDELAY"					     
#define		RCV_TRACE_ACTUALSPEED_FLAGRECORDINGMODE						        "RCV_TRACE_ACTUALSPEED_FLAGRECORDINGMODE"						     
#define		RCV_TRACE_PRESSURESETPOINT_POSNPRETRIGGERDELAY				        "RCV_TRACE_PRESSURESETPOINT_POSNPRETRIGGERDELAY"				     
#define		RCV_TRACE_PRESSURESETPOINT_FLAGRECORDINGMODE				        "RCV_TRACE_PRESSURESETPOINT_FLAGRECORDINGMODE"				         
#define		RCV_TRACE_SPEEDSETPOINT_POSNPRETRIGGERDELAY					        "RCV_TRACE_SPEEDSETPOINT_POSNPRETRIGGERDELAY"					     
#define		RCV_TRACE_SPEEDSETPOINT_FLAGRECORDINGMODE					        "RCV_TRACE_SPEEDSETPOINT_FLAGRECORDINGMODE"					     
#define		INJ_TRACE_ACTUALHOLDPRESSURE_TMPRETRIGGERDELAY				        "INJ_TRACE_ACTUALHOLDPRESSURE_TMPRETRIGGERDELAY"				     
#define		INJ_TRACE_ACTUALHOLDPRESSURE_FLAGRECORDINGMODE				        "INJ_TRACE_ACTUALHOLDPRESSURE_FLAGRECORDINGMODE"				     
#define		INJ_TRACE_ACTUALINJPRESSURE_POSNPRETRIGGERDELAY				        "INJ_TRACE_ACTUALINJPRESSURE_POSNPRETRIGGERDELAY"				     
#define		INJ_TRACE_ACTUALINJPRESSURE_FLAGRECORDINGMODE				        "INJ_TRACE_ACTUALINJPRESSURE_FLAGRECORDINGMODE"				     
#define		INJ_TRACE_ACTUALINJVELOCITY_POSNPRETRIGGERDELAY				        "INJ_TRACE_ACTUALINJVELOCITY_POSNPRETRIGGERDELAY"				     
#define		INJ_TRACE_ACTUALINJVELOCITY_FLAGRECORDINGMODE				        "INJ_TRACE_ACTUALINJVELOCITY_FLAGRECORDINGMODE"				     
#define		INJ_TRACE_ACTUALTRANSITIONPOSITION_TMPRETRIGGERDELAY		        "INJ_TRACE_ACTUALTRANSITIONPOSITION_TMPRETRIGGERDELAY"		         
#define		INJ_TRACE_ACTUALTRANSITIONPOSITION_FLAGRECORDINGMODE		        "INJ_TRACE_ACTUALTRANSITIONPOSITION_FLAGRECORDINGMODE"		         
#define		INJ_TRACE_ACTUALTRANSITIONPRESSURE_TMPRETRIGGERDELAY		        "INJ_TRACE_ACTUALTRANSITIONPRESSURE_TMPRETRIGGERDELAY"		         
#define		INJ_TRACE_ACTUALTRANSITIONPRESSURE_FLAGRECORDINGMODE		        "INJ_TRACE_ACTUALTRANSITIONPRESSURE_FLAGRECORDINGMODE"		         
#define		INJ_TRACE_ACTUALTRANSITIONVELOCITY_TMPRETRIGGERDELAY		        "INJ_TRACE_ACTUALTRANSITIONVELOCITY_TMPRETRIGGERDELAY"		         
#define		INJ_TRACE_ACTUALTRANSITIONVELOCITY_FLAGRECORDINGMODE		        "INJ_TRACE_ACTUALTRANSITIONVELOCITY_FLAGRECORDINGMODE"		         
#define		INJ_TRACE_HOLDPRESSURESETPOINT_TMPRETRIGGERDELAY			        "INJ_TRACE_HOLDPRESSURESETPOINT_TMPRETRIGGERDELAY"			         
#define		INJ_TRACE_HOLDPRESSURESETPOINT_FLAGRECORDINGMODE			        "INJ_TRACE_HOLDPRESSURESETPOINT_FLAGRECORDINGMODE"			         
#define		INJ_TRACE_INJPRESSURELIMITSETPOINT_POSNPRETRIGGERDELAY		        "INJ_TRACE_INJPRESSURELIMITSETPOINT_POSNPRETRIGGERDELAY"		     
#define		INJ_TRACE_INJPRESSURELIMITSETPOINT_FLAGRECORDINGMODE		        "INJ_TRACE_INJPRESSURELIMITSETPOINT_FLAGRECORDINGMODE"		         
#define		INJ_TRACE_INTERPOLATEDVELOCITYSETPOINT_POSNPRETRIGGERDELAY	        "INJ_TRACE_INTERPOLATEDVELOCITYSETPOINT_POSNPRETRIGGERDELAY"	     
#define		INJ_TRACE_INTERPOLATEDVELOCITYSETPOINT_FLAGRECORDINGMODE	        "INJ_TRACE_INTERPOLATEDVELOCITYSETPOINT_FLAGRECORDINGMODE"	         
#define		DIAGNOSTIC_STARTUPTASKDONE	                                        "DIAGNOSTIC_STARTUPTASKDONE"						//400010003                          
#define		DIAGNOSTIC_DEFAULTTASKDONE	                                        "DIAGNOSTIC_DEFAULTTASKDONE"						//400010008                          
#define		DIAGNOSTIC_RESTARTTASKDONE                                          "DIAGNOSTIC_RESTARTTASKDONE"						//400010013                          
#define		MLD_CONFIG_POSNMAXMOLDHEIGTH                                        "MLD_CONFIG_POSNMAXMOLDHEIGTH"                                      
#define		INJ_PROFLMT_INJVELOCITY_POSNMAX                                 	"INJ_PROFLMT_INJVELOCITY_POSNMAX"                              
#define		INJ_PROFLMT_INJVELOCITY_POSNMIN                                 	"INJ_PROFLMT_INJVELOCITY_POSNMIN"
#define		RCV_INTERFACE_PRESACTUAL											"RCV_INTERFACE_PRESACTUAL"
#define		COMMAND__IPC_OPERATINGMODE											"COMMAND__IPC_OPERATINGMODE"
#define		TECH_SYSTEM_IDLETIME												"TECH_SYSTEM_IDLETIME"
#define		INJ_AXIS_FORCESTATEDATA_FORCECOMMANDVALUE							"INJ_AXIS_FORCESTATEDATA_FORCECOMMANDVALUE"			
#define		INJ_AXIS_FORCECONTROLLERDATA_FORCETOTALCOMMANDVALUE                 "INJ_AXIS_FORCECONTROLLERDATA_FORCETOTALCOMMANDVALUE" 
#define		INJ_AXIS_DATASETMONITORING_FORCEACTUALDATASET                       "INJ_AXIS_DATASETMONITORING_FORCEACTUALDATASET"       
#define		MLD_INTERFACE_TORQUEMAXDRIVECLAMPUP									"MLD_INTERFACE_TORQUEMAXDRIVECLAMPUP"
#define		MLD_INTERFACE_TORQUEACTUALDRIVE										"MLD_INTERFACE_TORQUEACTUALDRIVE"
/*==========================================================================+
|           Control			                                                |
+==========================================================================*/
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS1_VELY            	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS1_VELY"               
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS2_VELY            	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS2_VELY"               
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS3_VELY            	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS3_VELY"               
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS4_VELY            	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS4_VELY"               
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS5_VELY            	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS5_VELY"               
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS6_VELY            	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS6_VELY"               
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS7_VELY            	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS7_VELY"               
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS8_VELY            	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS8_VELY"               
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS9_VELY            	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS9_VELY"               
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS10_VELY           	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS10_VELY"              
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS1_POSNX           	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS1_POSNX"              
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS2_POSNX           	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS2_POSNX"              
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS3_POSNX           	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS3_POSNX"              
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS4_POSNX           	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS4_POSNX"              
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS5_POSNX           	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS5_POSNX"              
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS6_POSNX           	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS6_POSNX"              
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS7_POSNX           	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS7_POSNX"              
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS8_POSNX           	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS8_POSNX"              
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS9_POSNX           	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS9_POSNX"              
#define		TECH_SYS_INJ_PROF_INJVELOCITY_POINTS10_POSNX          	"TECH_SYS_INJ_PROF_INJVELOCITY_POINTS10_POSNX"             
#define		TECH_SYS_INJ_CONFIG_FLAGINJECTIONMODE                 	"TECH_SYS_INJ_CONFIG_FLAGINJECTIONMODE"                    
#define		TECH_SYS_INJ_PROF_INJ_CNNOPROFILEPOINTS               	"TECH_SYS_INJ_PROF_INJ_CNNOPROFILEPOINTS"                  
//#define		TECH_SYS_INJ_PROF_INJVELOCITY_VELY                    	"TECH_SYS_INJ_PROF_INJVELOCITY_VELY"                       
//#define		TECH_SYS_INJ_PROF_INJVELOCITY_POSNX                   	"TECH_SYS_INJ_PROF_INJVELOCITY_POSNX"                      
#define		TECH_SYS_RCV_PROF_SPEED_POINTS1_RPMY                  	"TECH_SYS_RCV_PROF_SPEED_POINTS1_RPMY"                     
#define		TECH_SYS_RCV_PROF_SPEED_POINTS2_RPMY                  	"TECH_SYS_RCV_PROF_SPEED_POINTS2_RPMY"                     
#define		TECH_SYS_RCV_PROF_SPEED_POINTS3_RPMY                  	"TECH_SYS_RCV_PROF_SPEED_POINTS3_RPMY"                     
#define		TECH_SYS_RCV_PROF_SPEED_POINTS4_RPMY                  	"TECH_SYS_RCV_PROF_SPEED_POINTS4_RPMY"                     
#define		TECH_SYS_RCV_PROF_SPEED_POINTS5_RPMY                  	"TECH_SYS_RCV_PROF_SPEED_POINTS5_RPMY"                     
#define		TECH_SYS_RCV_PROF_SPEED_POINTS6_RPMY                  	"TECH_SYS_RCV_PROF_SPEED_POINTS6_RPMY"                     
#define		TECH_SYS_RCV_PROF_SPEED_POINTS7_RPMY                  	"TECH_SYS_RCV_PROF_SPEED_POINTS7_RPMY"                     
#define		TECH_SYS_RCV_PROF_SPEED_POINTS8_RPMY                  	"TECH_SYS_RCV_PROF_SPEED_POINTS8_RPMY"                     
#define		TECH_SYS_RCV_PROF_SPEED_POINTS9_RPMY                  	"TECH_SYS_RCV_PROF_SPEED_POINTS9_RPMY"                     
#define		TECH_SYS_RCV_PROF_SPEED_POINTS10_RPMY                 	"TECH_SYS_RCV_PROF_SPEED_POINTS10_RPMY"                    
#define		TECH_SYS_RCV_PROF_SPEED_POINTS1_POSNX                 	"TECH_SYS_RCV_PROF_SPEED_POINTS1_POSNX"                    
#define		TECH_SYS_RCV_PROF_SPEED_POINTS2_POSNX                 	"TECH_SYS_RCV_PROF_SPEED_POINTS2_POSNX"                    
#define		TECH_SYS_RCV_PROF_SPEED_POINTS3_POSNX                 	"TECH_SYS_RCV_PROF_SPEED_POINTS3_POSNX"                    
#define		TECH_SYS_RCV_PROF_SPEED_POINTS4_POSNX                 	"TECH_SYS_RCV_PROF_SPEED_POINTS4_POSNX"                    
#define		TECH_SYS_RCV_PROF_SPEED_POINTS5_POSNX                 	"TECH_SYS_RCV_PROF_SPEED_POINTS5_POSNX"                    
#define		TECH_SYS_RCV_PROF_SPEED_POINTS6_POSNX                 	"TECH_SYS_RCV_PROF_SPEED_POINTS6_POSNX"                    
#define		TECH_SYS_RCV_PROF_SPEED_POINTS7_POSNX                 	"TECH_SYS_RCV_PROF_SPEED_POINTS7_POSNX"                    
#define		TECH_SYS_RCV_PROF_SPEED_POINTS8_POSNX                 	"TECH_SYS_RCV_PROF_SPEED_POINTS8_POSNX"                    
#define		TECH_SYS_RCV_PROF_SPEED_POINTS9_POSNX                 	"TECH_SYS_RCV_PROF_SPEED_POINTS9_POSNX"                    
#define		TECH_SYS_RCV_PROF_SPEED_POINTS10_POSNX                	"TECH_SYS_RCV_PROF_SPEED_POINTS10_POSNX"                   
#define		TECH_SYS_RCV_PROF_SPEED_CNNOPROFILEPOINTS             	"TECH_SYS_RCV_PROF_SPEED_CNNOPROFILEPOINTS"                
//#define		TECH_SYS_RCV_PROF_SPEED_RPMY                          	"TECH_SYS_RCV_PROF_SPEED_RPMY"                             
//#define		TECH_SYS_RCV_PROF_SPEED_POSNX                         	"TECH_SYS_RCV_PROF_SPEED_POSNX"                            
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_CNNOPROFILEPOINTS      	"TECH_SYS_MLD_PROF_VELOCITYOPEN_CNNOPROFILEPOINTS"         
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS1_POSNX          	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS1_POSNX"             
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS1_VELY           	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS1_VELY"              
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS1_FLAGSTOPPOINT  	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS1_FLAGSTOPPOINT"     
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS2_POSNX          	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS2_POSNX"             
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS2_VELY           	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS2_VELY"     
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS2_FLAGSTOPPOINT  	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS2_FLAGSTOPPOINT"     
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS3_POSNX          	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS3_POSNX"             
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS3_VELY           	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS3_VELY"              
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS3_FLAGSTOPPOINT  	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS3_FLAGSTOPPOINT"     
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS4_POSNX          	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS4_POSNX"             
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS4_VELY           	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS4_VELY"              
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS4_FLAGSTOPPOINT  	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS4_FLAGSTOPPOINT"     
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS5_POSNX          	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS5_POSNX"             
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS5_VELY           	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS5_VELY"              
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS5_FLAGSTOPPOINT  	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS5_FLAGSTOPPOINT"     
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS6_POSNX          	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS6_POSNX"             
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS6_VELY           	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS6_VELY"             
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS6_FLAGSTOPPOINT  	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS6_FLAGSTOPPOINT"     
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS7_POSNX          	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS7_POSNX"             
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS7_VELY           	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS7_VELY"              
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS7_FLAGSTOPPOINT  	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS7_FLAGSTOPPOINT"     
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS8_POSNX          	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS8_POSNX"             
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS8_VELY           	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS8_VELY"              
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS8_FLAGSTOPPOINT  	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS8_FLAGSTOPPOINT"     
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS9_POSNX          	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS9_POSNX"             
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS9_VELY           	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS9_VELY"              
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS9_FLAGSTOPPOINT  	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS9_FLAGSTOPPOINT"     
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS10_POSNX         	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS10_POSNX"            
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS10_VELY          	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS10_VELY"             
//#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POSNX                  	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POSNX"                     
//#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_VELY                   	"TECH_SYS_MLD_PROF_VELOCITYOPEN_VELY"                      
#define		TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS10_FLAGSTOPPOINT 	"TECH_SYS_MLD_PROF_VELOCITYOPEN_POINTS10_FLAGSTOPPOINT"    
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_CNNOPROFILEPOINTS     	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_CNNOPROFILEPOINTS"        
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS1_POSNX         	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS1_POSNX"            
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS1_VELY          	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS1_VELY"             
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS1_FLAGSTOPPOINT 	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS1_FLAGSTOPPOINT"    
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS2_POSNX         	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS2_POSNX"            
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS2_VELY          	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS2_VELY"             
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS2_FLAGSTOPPOINT 	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS2_FLAGSTOPPOINT"    
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS3_POSNX         	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS3_POSNX"            
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS3_VELY          	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS3_VELY"             
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS3_FLAGSTOPPOINT 	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS3_FLAGSTOPPOINT"    
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS4_POSNX         	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS4_POSNX"            
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS4_VELY          	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS4_VELY"             
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS4_FLAGSTOPPOINT 	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS4_FLAGSTOPPOINT"    
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS5_POSNX         	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS5_POSNX"            
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS5_VELY          	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS5_VELY"             
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS5_FLAGSTOPPOINT 	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS5_FLAGSTOPPOINT"    
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS6_POSNX         	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS6_POSNX"            
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS6_VELY          	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS6_VELY"             
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS6_FLAGSTOPPOINT 	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS6_FLAGSTOPPOINT"    
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS7_POSNX         	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS7_POSNX"            
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS7_VELY          	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS7_VELY"             
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS7_FLAGSTOPPOINT 	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS7_FLAGSTOPPOINT"    
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS8_POSNX         	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS8_POSNX"            
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS8_VELY          	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS8_VELY"             
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS8_FLAGSTOPPOINT 	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS8_FLAGSTOPPOINT"    
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS9_POSNX         	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS9_POSNX"            
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS9_VELY          	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS9_VELY"             
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS9_FLAGSTOPPOINT 	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS9_FLAGSTOPPOINT"    
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS10_POSNX        	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS10_POSNX"           
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS10_VELY         	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS10_VELY"            
#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS10_FLAGSTOPPOINT	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POINTS10_FLAGSTOPPOINT"   
#define		TECH_SYS_MLD_PROF_PROTECTION_FORCE                    	"TECH_SYS_MLD_PROF_PROTECTION_FORCE"                       
//#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_POSNX                 	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_POSNX"                    
//#define		TECH_SYS_MLD_PROF_VELOCITYCLOSE_VELY                  	"TECH_SYS_MLD_PROF_VELOCITYCLOSE_VELY"  

#define		INJ_PROF_INJVELOCITY_POINTS1_VELY            			"INJ_PROF_INJVELOCITY_POINTS1_VELY"               
#define		INJ_PROF_INJVELOCITY_POINTS2_VELY            			"INJ_PROF_INJVELOCITY_POINTS2_VELY"               
#define		INJ_PROF_INJVELOCITY_POINTS3_VELY            			"INJ_PROF_INJVELOCITY_POINTS3_VELY"               
#define		INJ_PROF_INJVELOCITY_POINTS4_VELY            			"INJ_PROF_INJVELOCITY_POINTS4_VELY"               
#define		INJ_PROF_INJVELOCITY_POINTS5_VELY            			"INJ_PROF_INJVELOCITY_POINTS5_VELY"               
#define		INJ_PROF_INJVELOCITY_POINTS6_VELY            			"INJ_PROF_INJVELOCITY_POINTS6_VELY"               
#define		INJ_PROF_INJVELOCITY_POINTS7_VELY            			"INJ_PROF_INJVELOCITY_POINTS7_VELY"               
#define		INJ_PROF_INJVELOCITY_POINTS8_VELY            			"INJ_PROF_INJVELOCITY_POINTS8_VELY"               
#define		INJ_PROF_INJVELOCITY_POINTS9_VELY            			"INJ_PROF_INJVELOCITY_POINTS9_VELY"               
#define		INJ_PROF_INJVELOCITY_POINTS10_VELY           			"INJ_PROF_INJVELOCITY_POINTS10_VELY"              
#define		INJ_PROF_INJVELOCITY_POINTS1_POSNX           			"INJ_PROF_INJVELOCITY_POINTS1_POSNX"              
#define		INJ_PROF_INJVELOCITY_POINTS2_POSNX           			"INJ_PROF_INJVELOCITY_POINTS2_POSNX"              
#define		INJ_PROF_INJVELOCITY_POINTS3_POSNX           			"INJ_PROF_INJVELOCITY_POINTS3_POSNX"              
#define		INJ_PROF_INJVELOCITY_POINTS4_POSNX           			"INJ_PROF_INJVELOCITY_POINTS4_POSNX"              
#define		INJ_PROF_INJVELOCITY_POINTS5_POSNX           			"INJ_PROF_INJVELOCITY_POINTS5_POSNX"              
#define		INJ_PROF_INJVELOCITY_POINTS6_POSNX           			"INJ_PROF_INJVELOCITY_POINTS6_POSNX"              
#define		INJ_PROF_INJVELOCITY_POINTS7_POSNX           			"INJ_PROF_INJVELOCITY_POINTS7_POSNX"              
#define		INJ_PROF_INJVELOCITY_POINTS8_POSNX           			"INJ_PROF_INJVELOCITY_POINTS8_POSNX"              
#define		INJ_PROF_INJVELOCITY_POINTS9_POSNX           			"INJ_PROF_INJVELOCITY_POINTS9_POSNX"              
#define		INJ_PROF_INJVELOCITY_POINTS10_POSNX          			"INJ_PROF_INJVELOCITY_POINTS10_POSNX"             
#define		INJ_CONFIG_FLAGINJECTIONMODE                 			"INJ_CONFIG_FLAGINJECTIONMODE"                    
//#define		INJ_PROF_INJ_CNNOPROFILEPOINTS               			"INJ_PROF_INJVELOCITY_CNNOPROFILEPOINTS"                  
//#define		INJ_PROF_INJVELOCITY_POINTS1_VELY                    	"INJ_PROF_INJVELOCITY_VELY"                       
//#define		INJ_PROF_INJVELOCITY_POSNX                   			"INJ_PROF_INJVELOCITY_POSNX"                      
#define		RCV_PROF_SPEED_POINTS1_RPMY                  			"RCV_PROF_SPEED_POINTS1_RPMY"                     
#define		RCV_PROF_SPEED_POINTS2_RPMY                  			"RCV_PROF_SPEED_POINTS2_RPMY"                     
#define		RCV_PROF_SPEED_POINTS3_RPMY                  			"RCV_PROF_SPEED_POINTS3_RPMY"                     
#define		RCV_PROF_SPEED_POINTS4_RPMY                  			"RCV_PROF_SPEED_POINTS4_RPMY"                     
#define		RCV_PROF_SPEED_POINTS5_RPMY                  			"RCV_PROF_SPEED_POINTS5_RPMY"                     
#define		RCV_PROF_SPEED_POINTS6_RPMY                  			"RCV_PROF_SPEED_POINTS6_RPMY"                     
#define		RCV_PROF_SPEED_POINTS7_RPMY                  			"RCV_PROF_SPEED_POINTS7_RPMY"                     
#define		RCV_PROF_SPEED_POINTS8_RPMY                  			"RCV_PROF_SPEED_POINTS8_RPMY"                     
#define		RCV_PROF_SPEED_POINTS9_RPMY                  			"RCV_PROF_SPEED_POINTS9_RPMY"                     
#define		RCV_PROF_SPEED_POINTS10_RPMY                 			"RCV_PROF_SPEED_POINTS10_RPMY"                    
#define		RCV_PROF_SPEED_POINTS1_POSNX                 			"RCV_PROF_SPEED_POINTS1_POSNX"                    
#define		RCV_PROF_SPEED_POINTS2_POSNX                 			"RCV_PROF_SPEED_POINTS2_POSNX"                    
#define		RCV_PROF_SPEED_POINTS3_POSNX                 			"RCV_PROF_SPEED_POINTS3_POSNX"                    
#define		RCV_PROF_SPEED_POINTS4_POSNX                 			"RCV_PROF_SPEED_POINTS4_POSNX"                    
#define		RCV_PROF_SPEED_POINTS5_POSNX                 			"RCV_PROF_SPEED_POINTS5_POSNX"                    
#define		RCV_PROF_SPEED_POINTS6_POSNX                 			"RCV_PROF_SPEED_POINTS6_POSNX"                    
#define		RCV_PROF_SPEED_POINTS7_POSNX                 			"RCV_PROF_SPEED_POINTS7_POSNX"                    
#define		RCV_PROF_SPEED_POINTS8_POSNX                 			"RCV_PROF_SPEED_POINTS8_POSNX"                    
#define		RCV_PROF_SPEED_POINTS9_POSNX                 			"RCV_PROF_SPEED_POINTS9_POSNX"                    
#define		RCV_PROF_SPEED_POINTS10_POSNX                			"RCV_PROF_SPEED_POINTS10_POSNX"                   
//#define		RCV_PROF_SPEED_CNNOPROFILEPOINTS             			"RCV_PROF_SPEED_CNNOPROFILEPOINTS"                
//#define		RCV_PROF_SPEED_RPMY                          			"RCV_PROF_SPEED_RPMY"                             
//#define		RCV_PROF_SPEED_POSNX                         			"RCV_PROF_SPEED_POSNX"                            
#define		MLD_PROF_VELOCITYOPEN_CNNOPROFILEPOINTS      			"MLD_PROF_VELOCITYOPEN_CNNOPROFILEPOINTS"         
#define		MLD_PROF_VELOCITYOPEN_POINTS1_POSNX          			"MLD_PROF_VELOCITYOPEN_POINTS1_POSNX"             
#define		MLD_PROF_VELOCITYOPEN_POINTS1_VELY           			"MLD_PROF_VELOCITYOPEN_POINTS1_VELY"              
#define		MLD_PROF_VELOCITYOPEN_POINTS1_FLAGSTOPPOINT  			"MLD_PROF_VELOCITYOPEN_POINTS1_FLAGSTOPPOINT"     
#define		MLD_PROF_VELOCITYOPEN_POINTS2_POSNX          			"MLD_PROF_VELOCITYOPEN_POINTS2_POSNX"             
#define		MLD_PROF_VELOCITYOPEN_POINTS2_VELY           			"MLD_PROF_VELOCITYOPEN_POINTS2_VELY"     
#define		MLD_PROF_VELOCITYOPEN_POINTS2_FLAGSTOPPOINT  			"MLD_PROF_VELOCITYOPEN_POINTS2_FLAGSTOPPOINT"     
#define		MLD_PROF_VELOCITYOPEN_POINTS3_POSNX          			"MLD_PROF_VELOCITYOPEN_POINTS3_POSNX"             
#define		MLD_PROF_VELOCITYOPEN_POINTS3_VELY           			"MLD_PROF_VELOCITYOPEN_POINTS3_VELY"              
#define		MLD_PROF_VELOCITYOPEN_POINTS3_FLAGSTOPPOINT  			"MLD_PROF_VELOCITYOPEN_POINTS3_FLAGSTOPPOINT"     
#define		MLD_PROF_VELOCITYOPEN_POINTS4_POSNX          			"MLD_PROF_VELOCITYOPEN_POINTS4_POSNX"             
#define		MLD_PROF_VELOCITYOPEN_POINTS4_VELY           			"MLD_PROF_VELOCITYOPEN_POINTS4_VELY"              
#define		MLD_PROF_VELOCITYOPEN_POINTS4_FLAGSTOPPOINT  			"MLD_PROF_VELOCITYOPEN_POINTS4_FLAGSTOPPOINT"     
#define		MLD_PROF_VELOCITYOPEN_POINTS5_POSNX          			"MLD_PROF_VELOCITYOPEN_POINTS5_POSNX"             
#define		MLD_PROF_VELOCITYOPEN_POINTS5_VELY           			"MLD_PROF_VELOCITYOPEN_POINTS5_VELY"              
#define		MLD_PROF_VELOCITYOPEN_POINTS5_FLAGSTOPPOINT  			"MLD_PROF_VELOCITYOPEN_POINTS5_FLAGSTOPPOINT"     
#define		MLD_PROF_VELOCITYOPEN_POINTS6_POSNX          			"MLD_PROF_VELOCITYOPEN_POINTS6_POSNX"             
#define		MLD_PROF_VELOCITYOPEN_POINTS6_VELY           			"MLD_PROF_VELOCITYOPEN_POINTS6_VELY"             
#define		MLD_PROF_VELOCITYOPEN_POINTS6_FLAGSTOPPOINT  			"MLD_PROF_VELOCITYOPEN_POINTS6_FLAGSTOPPOINT"     
#define		MLD_PROF_VELOCITYOPEN_POINTS7_POSNX          			"MLD_PROF_VELOCITYOPEN_POINTS7_POSNX"             
#define		MLD_PROF_VELOCITYOPEN_POINTS7_VELY           			"MLD_PROF_VELOCITYOPEN_POINTS7_VELY"              
#define		MLD_PROF_VELOCITYOPEN_POINTS7_FLAGSTOPPOINT  			"MLD_PROF_VELOCITYOPEN_POINTS7_FLAGSTOPPOINT"     
#define		MLD_PROF_VELOCITYOPEN_POINTS8_POSNX          			"MLD_PROF_VELOCITYOPEN_POINTS8_POSNX"             
#define		MLD_PROF_VELOCITYOPEN_POINTS8_VELY           			"MLD_PROF_VELOCITYOPEN_POINTS8_VELY"              
#define		MLD_PROF_VELOCITYOPEN_POINTS8_FLAGSTOPPOINT  			"MLD_PROF_VELOCITYOPEN_POINTS8_FLAGSTOPPOINT"     
#define		MLD_PROF_VELOCITYOPEN_POINTS9_POSNX          			"MLD_PROF_VELOCITYOPEN_POINTS9_POSNX"             
#define		MLD_PROF_VELOCITYOPEN_POINTS9_VELY           			"MLD_PROF_VELOCITYOPEN_POINTS9_VELY"              
#define		MLD_PROF_VELOCITYOPEN_POINTS9_FLAGSTOPPOINT  			"MLD_PROF_VELOCITYOPEN_POINTS9_FLAGSTOPPOINT"     
#define		MLD_PROF_VELOCITYOPEN_POINTS10_POSNX         			"MLD_PROF_VELOCITYOPEN_POINTS10_POSNX"            
#define		MLD_PROF_VELOCITYOPEN_POINTS10_VELY          			"MLD_PROF_VELOCITYOPEN_POINTS10_VELY"             
//#define		MLD_PROF_VELOCITYOPEN_POSNX                  			"MLD_PROF_VELOCITYOPEN_POSNX"                     
//#define		MLD_PROF_VELOCITYOPEN_VELY                   			"MLD_PROF_VELOCITYOPEN_VELY"                      
#define		MLD_PROF_VELOCITYOPEN_POINTS10_FLAGSTOPPOINT 			"MLD_PROF_VELOCITYOPEN_POINTS10_FLAGSTOPPOINT"    
#define		MLD_PROF_VELOCITYCLOSE_CNNOPROFILEPOINTS     			"MLD_PROF_VELOCITYCLOSE_CNNOPROFILEPOINTS"        
#define		MLD_PROF_VELOCITYCLOSE_POINTS1_POSNX         			"MLD_PROF_VELOCITYCLOSE_POINTS1_POSNX"            
#define		MLD_PROF_VELOCITYCLOSE_POINTS1_VELY          			"MLD_PROF_VELOCITYCLOSE_POINTS1_VELY"             
#define		MLD_PROF_VELOCITYCLOSE_POINTS1_FLAGSTOPPOINT 			"MLD_PROF_VELOCITYCLOSE_POINTS1_FLAGSTOPPOINT"    
#define		MLD_PROF_VELOCITYCLOSE_POINTS2_POSNX         			"MLD_PROF_VELOCITYCLOSE_POINTS2_POSNX"            
#define		MLD_PROF_VELOCITYCLOSE_POINTS2_VELY          			"MLD_PROF_VELOCITYCLOSE_POINTS2_VELY"             
#define		MLD_PROF_VELOCITYCLOSE_POINTS2_FLAGSTOPPOINT 			"MLD_PROF_VELOCITYCLOSE_POINTS2_FLAGSTOPPOINT"    
#define		MLD_PROF_VELOCITYCLOSE_POINTS3_POSNX         			"MLD_PROF_VELOCITYCLOSE_POINTS3_POSNX"            
#define		MLD_PROF_VELOCITYCLOSE_POINTS3_VELY          			"MLD_PROF_VELOCITYCLOSE_POINTS3_VELY"             
#define		MLD_PROF_VELOCITYCLOSE_POINTS3_FLAGSTOPPOINT 			"MLD_PROF_VELOCITYCLOSE_POINTS3_FLAGSTOPPOINT"    
#define		MLD_PROF_VELOCITYCLOSE_POINTS4_POSNX         			"MLD_PROF_VELOCITYCLOSE_POINTS4_POSNX"            
#define		MLD_PROF_VELOCITYCLOSE_POINTS4_VELY          			"MLD_PROF_VELOCITYCLOSE_POINTS4_VELY"             
#define		MLD_PROF_VELOCITYCLOSE_POINTS4_FLAGSTOPPOINT 			"MLD_PROF_VELOCITYCLOSE_POINTS4_FLAGSTOPPOINT"    
#define		MLD_PROF_VELOCITYCLOSE_POINTS5_POSNX         			"MLD_PROF_VELOCITYCLOSE_POINTS5_POSNX"            
#define		MLD_PROF_VELOCITYCLOSE_POINTS5_VELY          			"MLD_PROF_VELOCITYCLOSE_POINTS5_VELY"             
#define		MLD_PROF_VELOCITYCLOSE_POINTS5_FLAGSTOPPOINT 			"MLD_PROF_VELOCITYCLOSE_POINTS5_FLAGSTOPPOINT"    
#define		MLD_PROF_VELOCITYCLOSE_POINTS6_POSNX         			"MLD_PROF_VELOCITYCLOSE_POINTS6_POSNX"            
#define		MLD_PROF_VELOCITYCLOSE_POINTS6_VELY          			"MLD_PROF_VELOCITYCLOSE_POINTS6_VELY"             
#define		MLD_PROF_VELOCITYCLOSE_POINTS6_FLAGSTOPPOINT 			"MLD_PROF_VELOCITYCLOSE_POINTS6_FLAGSTOPPOINT"    
#define		MLD_PROF_VELOCITYCLOSE_POINTS7_POSNX         			"MLD_PROF_VELOCITYCLOSE_POINTS7_POSNX"            
#define		MLD_PROF_VELOCITYCLOSE_POINTS7_VELY          			"MLD_PROF_VELOCITYCLOSE_POINTS7_VELY"             
#define		MLD_PROF_VELOCITYCLOSE_POINTS7_FLAGSTOPPOINT 			"MLD_PROF_VELOCITYCLOSE_POINTS7_FLAGSTOPPOINT"    
#define		MLD_PROF_VELOCITYCLOSE_POINTS8_POSNX         			"MLD_PROF_VELOCITYCLOSE_POINTS8_POSNX"            
#define		MLD_PROF_VELOCITYCLOSE_POINTS8_VELY          			"MLD_PROF_VELOCITYCLOSE_POINTS8_VELY"             
#define		MLD_PROF_VELOCITYCLOSE_POINTS8_FLAGSTOPPOINT 			"MLD_PROF_VELOCITYCLOSE_POINTS8_FLAGSTOPPOINT"    
#define		MLD_PROF_VELOCITYCLOSE_POINTS9_POSNX         			"MLD_PROF_VELOCITYCLOSE_POINTS9_POSNX"            
#define		MLD_PROF_VELOCITYCLOSE_POINTS9_VELY          			"MLD_PROF_VELOCITYCLOSE_POINTS9_VELY"             
#define		MLD_PROF_VELOCITYCLOSE_POINTS9_FLAGSTOPPOINT 			"MLD_PROF_VELOCITYCLOSE_POINTS9_FLAGSTOPPOINT"    
#define		MLD_PROF_VELOCITYCLOSE_POINTS10_POSNX        			"MLD_PROF_VELOCITYCLOSE_POINTS10_POSNX"           
#define		MLD_PROF_VELOCITYCLOSE_POINTS10_VELY         			"MLD_PROF_VELOCITYCLOSE_POINTS10_VELY"            
#define		MLD_PROF_VELOCITYCLOSE_POINTS10_FLAGSTOPPOINT			"MLD_PROF_VELOCITYCLOSE_POINTS10_FLAGSTOPPOINT"   
#define		MLD_PROF_PROTECTION_FORCE                    			"MLD_PROF_PROTECTION_FORCE"                       
//#define		MLD_PROF_VELOCITYCLOSE_POSNX                 			"MLD_PROF_VELOCITYCLOSE_POSNX"                    
//#define		MLD_PROF_VELOCITYCLOSE_VELY                  			"MLD_PROF_VELOCITYCLOSE_VELY"  
#define		TECH_SYS_MLD_GENER_POSNMOLDOPENPOSITION					"TECH_SYS_MLD_GENER_POSNMOLDOPENPOSITION"				//	開模行程備份        
#define		TECH_SYS_INJ_TRANSITION_FLAGTRANSITIONCONDITION1		"TECH_SYS_INJ_TRANSITION_FLAGTRANSITIONCONDITION1"		//	轉換條件選擇備份    
#define		TECH_SYS_INJ_TRANSITION_POSNTRANSITION					"TECH_SYS_INJ_TRANSITION_POSNTRANSITION"				//	轉換條件選擇位置備份
#define		TECH_SYS_RCV_CONFIG_FLAGPRESSURECONTROLMODE				"TECH_SYS_RCV_CONFIG_FLAGPRESSURECONTROLMODE"			//	儲料背壓選擇備份    
#define		INJ_TRANSITION_POSNTRANSITION							"INJ_TRANSITION_POSNTRANSITION"							//	轉換條件選擇位置備份
#define		INJ_TRANSITION_FLAGTRANSITIONCONDITION1					"INJ_TRANSITION_FLAGTRANSITIONCONDITION1"				//	轉換條件選擇備份
#define		RCV_CONFIG_FLAGPRESSURECONTROLMODE						"RCV_CONFIG_FLAGPRESSURECONTROLMODE"					//	儲料背壓選擇備份 
/*==========================================================================+
|           Init			                                                |
+==========================================================================*/
#define		TECH_SYSTEM_LANGUAGEID												"TECH_SYSTEM_LANGUAGEID"
#endif          
