/* Copyright (C), 1996-2006, Techmation. Co., Ltd.*/ 

/*==========================================================================+
|  Class    : Porperty		   				  								|
|  Task     : Porperty header file          			      				|
|---------------------------------------------------------------------------|
|  Compile  :G++(GCC) 3.2                                                   |
|  Link     :G++(GCC) 3.2                                                   |
|  Call     :                                                               |
|---------------------------------------------------------------------------|
|  Author   : James		                                                  	|
|  Version  : V1.00                                                         |
|  Creation : 2010/08/11                                        	        |
|  Revision :                                                               |
+==========================================================================*/


#include "common.h"
#include "wnd.h"
#include "propertylist.h"

CLASSLIST	tm_ClassList;

CLASSPROPERTY tm_cszWnd[] = 
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64}
};
	
CLASSPROPERTY tm_cszEdit[] = 
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"type",						tmWORD},
	{"prompt",						tmUSTR},
	{"promptID",					tmSTR},
	{"maxchar",						tmWORD},
	{"echo",						tmWORD},
	{"text",						tmSTR},
	{"align",						tmWORD}
};

CLASSPROPERTY tm_cszEditX1[] = 
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"type",						tmWORD},
	{"prompt",						tmUSTR},
	{"promptID",					tmSTR},
	{"maxchar",						tmWORD},
	{"echo",						tmWORD},
	{"text",						tmSTR},
	{"align",						tmWORD},
	{"precision",					tmWORD},
	{"value",						tmINT64},
	{"min",							tmINT64},
	{"max",							tmINT64},
	{"minid",						tmSTR},
	{"maxid",						tmSTR},
	{"maxdb",						tmBOOL},
	{"mindb",						tmBOOL},
	{"maxEditName",					tmSTR},
	{"minEditName",					tmSTR},
	{"spepre",						tmINT},
	{"dbid0",						tmSTR},
	{"dbid1",						tmSTR},
	{"dbid2",						tmSTR},
	{"dbid3",						tmSTR},
	{"dbid4",						tmSTR},
	{"dbid5",						tmSTR},
	{"dbid6",						tmSTR},
	{"dbid7",						tmSTR},
	{"dbid8",						tmSTR},
	{"dbid9",						tmSTR}
};

CLASSPROPERTY tm_cszEditX2[] = 
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"type",						tmWORD},
	{"prompt",						tmUSTR},
	{"promptID",					tmSTR},
	{"maxchar",						tmWORD},
	{"echo",						tmWORD},
	{"text",						tmSTR},
	{"align",						tmWORD},
	{"value",						tmINT64},
	{"min",							tmINT64},
	{"max",							tmINT64},
	{"dbid0",						tmSTR},
	{"dbid1",						tmSTR},
	{"dbid2",						tmSTR},
	{"dbid3",						tmSTR},
	{"dbid4",						tmSTR},
	{"dbid5",						tmSTR},
	{"dbid6",						tmSTR},
	{"dbid7",						tmSTR},
	{"dbid8",						tmSTR},
	{"dbid9",						tmSTR}
};

CLASSPROPERTY tm_cszSelectEdit[] = 
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"dbid0",						11},	
	{"dbid1",        				11},	
	{"dbid2",        				11},	
	{"dbid3",        				11},	
	{"dbid4",        				11},	
	{"dbid5",        				11},	
	{"dbid6",        				11},	
	{"dbid7",        				11},	
	{"dbid8",        				11},	
	{"dbid9",        				11},	
	{"startvalue",     				2 },	
	{"maxindex ",      				3 },	
	{"str0",       					12},	
	{"strID0",         				11},	
	{"str1",        				12},	
	{"strID1",       		 		11},	
	{"str2",        				12},	
	{"strID2",         				11},	
	{"str3",       					12},	
	{"strID3",        				11},	
	{"str4",     					12},	
	{"strID4",         				11},	
	{"str5",         				12},	
	{"strID5",         				11},	
	{"str6",          				12},	
	{"strID6",         				11},	
	{"str7",           				12},	
	{"strID7",         				11},	
	{"str8",         				12},	
	{"strID8",         				11},	
	{"str9",         				12},	
	{"strID9",         				11},	
	{"str10",         				12},	
	{"strID10",        				11},	
	{"str11",        				12},	
	{"strID11",        				11},	
	{"str12",        				12},	
	{"strID12",        				11},	
	{"str13",       				12},	
	{"strID13",      				11},	
	{"str14",        				12},	
	{"strID14",        				11},	
	{"str15",        				12},	
	{"strID15",        				11},	
	{"str16",       				12},	
	{"strID16",        				11},	
	{"str17",        				12},	
	{"strID17",        				11},	
	{"str18",          				12},	
	{"strID18",        				11},	
	{"str19",          				12},	
	{"strID19",        				11},	
	{"maxchar",        				3 },	
	{"stype",          				3 },	
	{"prompt",   					12},	
	{"promptID",       				11},	
	{"focuscolor",     				4 },	
	{"listnum",        				3 }

};

CLASSPROPERTY tm_cszSelectBox[] = 
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"selected",					14},   
	{"text",    					12},   
	{"prompt", 						12},   
	{"textID", 						11},   
	{"promptID",					11},   
	{"group",  						2 }
};

CLASSPROPERTY tm_cszSelectBit[] = 
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"dbid0",         11},
	{"dbid1",         11},
	{"dbid2",         11},
	{"dbid3",         11},
	{"dbid4",         11},
	{"dbid5",         11},
	{"dbid6",         11},
	{"dbid7",         11},
	{"dbid8",         11},
	{"dbid9",         11},
	{"startvalue",    2 },
	{"maxindex",      3 },
	{"str0",        12},
	{"strID0",       11},
	{"str1",      12},
	{"strID1",        11},
	{"str2",       12},
	{"strID2",        11},
	{"str3",       12},
	{"strID3",        11},
	{"str4",        12},
	{"strID4",        11},
	{"str5",        12},
	{"strID5",        11},
	{"str6",        12},
	{"strID6",       11},
	{"str7",        12},
	{"strID7",        11},
	{"str8",       12},
	{"strID8",        11},
	{"str9",       12},
	{"strID9",        11},
	{"str10",       12},
	{"strID10",       11},
	{"str11",        12},
	{"strID11",       11},
	{"str12",        12},
	{"strID12",       11},
	{"str13",       12},
	{"strID13",       11},
	{"str14",       12},
	{"strID14",       11},
	{"str15",        12},
	{"strID15",       11},
	{"str16",       12},
	{"strID16",       11},
	{"str17",       12},
	{"strID17",       11},
	{"str18",        12},
	{"strID18",       11},
	{"str19",       12},
	{"strID19",       11},
	{"maxchar",       3 },
	{"stype",        3 },
	{"prompt",      12},
	{"promptID",      11},
	{"focuscolor",    4 },
	{"listnum",     3 },
	{"dbid0",      11},
	{"bitindex",      2 },
	{"bitvalue",      3 }
};

CLASSPROPERTY tm_cszStaticX2[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"align",						3},
	{"text",						12},
	{"textID",						11},
	{"textID1",						11},
	{"textID2",						11},
	{"textID3",						11},
	{"textID4",						11},
	{"textID5",						11},
	{"textID6",						11},
	{"textID7",						11},
	{"textID8",						11},
	{"textID9",						11},
	{"textID10",					11}
};

CLASSPROPERTY tm_cszButton[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"buttontype",  	3 },	
	{"align",     		3 },	
	{"space",     		2 },	
	{"caption",    		12},	
	{"captionID",   	11},	
	{"upbitmap",    	11},	
	{"downbitmap",  	11},	
	{"captionID0",  	11},	
	{"captionID1",  	11},	
	{"captionID2",  	11},	
	{"captionID3",  	11},	
	{"captionID4",  	11},	
	{"captionID5",  	11},	
	{"captionID6",  	11},	
	{"captionID7",  	11},	
	{"captionID8",  	11},	
	{"captionID9",  	11},	
	{"keycolor",     	5},	
	{"captiontype",     3}
};

CLASSPROPERTY tm_cszToolButton[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"buttontype",  3 },	
	{"align",     3 },	
	{"space",     2 },	
	{"caption",    12},	
	{"captionID",   11},	
	{"upbitmap",    11},	
	{"downbitmap",  11},	
	{"captionID0",  11},	
	{"captionID1",  11},	
	{"captionID2",  11},	
	{"captionID3",  11},	
	{"captionID4",  11},	
	{"captionID5",  11},	
	{"captionID6",  11},	
	{"captionID7",  11},	
	{"captionID8",  11},	
	{"captionID9",  11},
	{"keycolor",     5},
	{"captiontype",  3},	
	{"key",         3 },	
	{"group",       3 },	
	{"action",      3 },	
	{"formname",    11},	
	{"barname",     11}
};

CLASSPROPERTY tm_cszImageBox[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"type",       					3 },	
	{"style",       				3 },	
	{"imagepath",   				11},	
	{"keycolor",    				5 },	
	{"doublebuffer",				14},	
	{"clickview",   				11}
};

CLASSPROPERTY tm_cszToolBar[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"bmpbackpath",  11},	
	{"bmpuppath",    11},	
	{"bmpdownpath",  11},	
	{"maintool",     11},	
	{"OnKeyA",       16},	
	{"OnKeyAEnd",    16},	
	{"OnMessage",    16},
	{"keycolor",     5}
};

CLASSPROPERTY tm_cszPromptBar[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64}
};

CLASSPROPERTY tm_cszStatusBar[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"OnUpdateA",  16},
	{"OnCreateA",  16},
	{"OnDestroyA", 16},
	{"OnMessage",  16}
};

CLASSPROPERTY tm_cszMainFrame[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"toolbar",						11}
};

CLASSPROPERTY tm_cszView[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"overviewname",				11},
	{"bmpbackpath",					11}

};

CLASSPROPERTY tm_cszFormView[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	//{"title",          11},
	//{"titleID",        11},
	{"bmpbackpath",    11},
	{"OnChangeA",      16},
	{"OnChangeBM",     16},
	{"OnCreateA",      16},
	{"OnShowA",        16},
	{"OnKeyA",         16},
	{"OnUpdateA",      16},
	{"OnDestroyA",     16},
	{"OnMessage",      16},
	{"pageno",         11},
	{"OnUpdateB",      16},
	{"printname",      11},
	{"canstop",        14},
	{"privateupdate",  14},
	{"savekey",        3 }

};

CLASSPROPERTY tm_cszDialog[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"bmpbackpath",					tmSTR}
};

CLASSPROPERTY tm_cszWndSplash[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"logopath", 					11}
};

CLASSPROPERTY tm_cszCartoon[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"showtype",        3 },	
	{"cartoonmin",      2 },	
	{"cartoonmax",      2 },	
	{"cartoonminID",    11},	
	{"cartoonmaxID",    11},	
	{"framecount",      3 },	
	{"bmpindex",       3 },	
	{"framebmppath0",   11},	
	{"framemin0",       2 },	
	{"framemax0",       2 },	
	{"framebmppath1",   11},	
	{"framemin1",       2 },	
	{"framemax1",       2 },	
	{"framebmppath2",   11},	
	{"framemin2",       2 },	
	{"framemax2",       2 },	
	{"framebmppath3",   11},	
	{"framemin3",       2 },	
	{"framemax3",       2 },	
	{"framebmppath4",   11},	
	{"framemin4",      2 },	
	{"framemax4",       2 },	
	{"framebmppath5",   11},	
	{"framemin5",       2 },	
	{"framemax5",       2 },	
	{"framebmppath6",   11},	
	{"framemin6",       2 },	
	{"framemax6",       2 },	
	{"framebmppath7",   11},	
	{"framemin7",       2 },	
	{"framemax7",       2 },	
	{"framebmppath8",   11},	
	{"framemin8",      2 },	
	{"framemax8",       2 },	
	{"framebmppath9",   11},	
	{"framemin9",       2 },	
	{"framemax9",       2 },	
	{"framebmppath10",  11},	
	{"framemin10",      2 },	
	{"framemax10",      2 },	
	{"framebmppath11",  11},	
	{"framemin11",      2 },	
	{"framemax11",      2 },	
	{"framebmppath12",  11},	
	{"framemin12",      2 },	
	{"framemax12",      2 },	
	{"framebmppath13",  11},	
	{"framemin13",      2 },	
	{"framemax13",      2 },	
	{"framebmppath14",  11},	
	{"framemin14",      2 },	
	{"framemax14",      2 },	
	{"framebmppath15",  11},	
	{"framemin15",      2 },	
	{"framemax15",      2 },	
	{"framebmppath16",  11},	
	{"framemin16",      2 },	
	{"framemax16",      2 },	
	{"framebmppath17",  11},	
	{"framemin17",      2 },	
	{"framemax17",      2 },	
	{"framebmppath18",  11},	
	{"framemin18",      2 },	
	{"framemax18",      2 },	
	{"framebmppath19",  11},	
	{"framemin19",      2 },	
	{"framemax19",      2 },	
	{"framebmppath20",  11},	
	{"framemin20",      2 },	
	{"framemax20",      2 },	
	{"framebmppath21",  11},	
	{"framemin21",      2 },	
	{"framemax21",      2 },	
	{"framebmppath22",  11},	
	{"framemin22",   	2 },	
	{"framemax22",      2 }
};

CLASSPROPERTY tm_cszValueInt[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"value0",    2},
	{"value1",    2},
	{"value2",    2},
	{"value3",    2},
	{"value4",    2},
	{"value5",    2},
	{"value6",    2},
	{"value7",    2},
	{"value8",    2},
	{"value9",    2},
	{"value10",   2},
	{"value11",   2},
	{"value12",   2},
	{"value13",   2},
	{"value14",   2},
	{"value15",   2},
	{"value16",   2},
	{"value17",   2},
	{"value18",   2},
	{"value19",   2},
	{"value20",   2},
	{"value21",   2},
	{"value22",   2},
	{"value23",   2},
	{"value24",   2},
	{"value25",   2},
	{"value26",   2},
	{"value27",   2},
	{"value28",   2},
	{"value29",   2},
	{"value30",   2},
	{"value31",   2},
	{"value32",   2},
	{"value33",   2},
	{"value34",   2},
	{"value35",   2},
	{"value36",   2},
	{"value37",   2},
	{"value38",   2},
	{"value39",   2},
	{"value40",   2},
	{"value41",   2},
	{"value42",   2},
	{"value43",   2},
	{"value44",   2},
	{"value45",   2},
	{"value46",   2},
	{"value47",   2},
	{"value48",   2},
	{"value49",   2},
	{"value50",   2},
	{"value51",   2},
	{"value52",   2},
	{"value53",   2},
	{"value54",   2},
	{"value55",   2},
	{"value56",   2},
	{"value57",   2},
	{"value58",   2},
	{"value59",   2},
	{"value60",   2},
	{"value61",   2},
	{"value62",   2},
	{"value63",   2},
	{"value64",   2},
	{"value65",   2},
	{"value66",   2},
	{"value67",   2},
	{"value68",   2},
	{"value69",   2},
	{"value70",   2},
	{"value71",   2},
	{"value72",   2},
	{"value73",   2},
	{"value74",   2},
	{"value75",   2},
	{"value76",   2},
	{"value77",   2},
	{"value78",   2},
	{"value79",   2},
	{"value80",   2},
	{"value81",   2},
	{"value82",   2},
	{"value83",   2},
	{"value84",   2},
	{"value85",   2},
	{"value86",   2},
	{"value87",   2},
	{"value88",   2},
	{"value89",   2},
	{"value90",   2},
	{"value91",   2},
	{"value92",   2},
	{"value93",   2},
	{"value94",   2},
	{"value95",   2},
	{"value96",   2},
	{"value97",   2},
	{"value98",   2},
	{"value99",   2},
	{"value100",  2},
	{"value101",  2},
	{"value102",  2},
	{"value103",  2},
	{"value104",  2},
	{"value105",  2},
	{"value106",  2},
	{"value107",  2},
	{"value108",  2},
	{"value109",  2},
	{"value110",  2},
	{"value111",  2},
	{"value112",  2},
	{"value113",  2},
	{"value114",  2},
	{"value115",  2},
	{"value116",  2},
	{"value117",  2},
	{"value118",  2},
	{"value119",  2},
	{"value120",  2},
	{"value121",  2},
	{"value122",  2},
	{"value123",  2},
	{"value124",  2},
	{"value125",  2},
	{"value126",  2},
	{"value127",  2},
	{"value128",  2},
	{"value129",  2},
	{"value130",  2},
	{"value131",  2},
	{"value132",  2},
	{"value133",  2},
	{"value134",  2},
	{"value135",  2},
	{"value136",  2},
	{"value137",  2},
	{"value138",  2},
	{"value139",  2},
	{"value140",  2},
	{"value141",  2},
	{"value142",  2},
	{"value143",  2},
	{"value144",  2},
	{"value145",  2},
	{"value146",  2},
	{"value147",  2},
	{"value148",  2},
	{"value149",  2},
	{"value150",  2},
	{"value151",  2},
	{"value152",  2},
	{"value153",  2},
	{"value154",  2},
	{"value155",  2},
	{"value156",  2},
	{"value157",  2},
	{"value158",  2},
	{"value159",  2},
	{"value160",  2},
	{"value161",  2},
	{"value162",  2},
	{"value163",  2},
	{"value164",  2},
	{"value165",  2},
	{"value166",  2},
	{"value167",  2},
	{"value168",  2},
	{"value169",  2},
	{"value170",  2},
	{"value171",  2},
	{"value172",  2},
	{"value173",  2},
	{"value174",  2},
	{"value175",  2},
	{"value176",  2},
	{"value177",  2},
	{"value178",  2},
	{"value179",  2},
	{"value180",  2},
	{"value181",  2},
	{"value182",  2},
	{"value183",  2},
	{"value184",  2},
	{"value185",  2},
	{"value186",  2},
	{"value187",  2},
	{"value188",  2},
	{"value189",  2},
	{"value190",  2},
	{"value191",  2},
	{"value192",  2},
	{"value193",  2},
	{"value194",  2},
	{"value195",  2},
	{"value196",  2},
	{"value197",  2},
	{"value198",  2},
	{"value199",  2},
	{"value200",  2},
	{"value201",  2},
	{"value202",  2},
	{"value203",  2},
	{"value204",  2},
	{"value205",  2},
	{"value206",  2},
	{"value207",  2},
	{"value208",  2},
	{"value209",  2},
	{"value210",  2},
	{"value211",  2},
	{"value212",  2},
	{"value213",  2},
	{"value214",  2},
	{"value215",  2},
	{"value216",  2},
	{"value217",  2},
	{"value218",  2},
	{"value219",  2},
	{"value220",  2},
	{"value221",  2},
	{"value222",  2},
	{"value223",  2},
	{"value224",  2},
	{"value225",  2},
	{"value226",  2},
	{"value227",  2},
	{"value228",  2},
	{"value229",  2},
	{"value230",  2},
	{"value231",  2},
	{"value232",  2},
	{"value233",  2},
	{"value234",  2},
	{"value235",  2},
	{"value236",  2},
	{"value237",  2},
	{"value238",  2},
	{"value239",  2},
	{"value240",  2},
	{"value241",  2},
	{"value242",  2},
	{"value243",  2},
	{"value244",  2},
	{"value245",  2},
	{"value246",  2},
	{"value247",  2},
	{"value248",  2},
	{"value249",  2},
	{"value250",  2},
	{"value251",  2},
	{"value252",  2},
	{"value253",  2},
	{"value254",  2},
	{"value255",  2},
	{"default",   2}
};

CLASSPROPERTY tm_cszLineTable[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"mainlinewidth", 1},	
	{"stype",         3},	
	{"maincolor.r",   0},	
	{"maincolor.g",   0},	
	{"maincolor.b",   0},	
	{"accrcolor1.r",  0},	
	{"accrcolor1.g",  0},	
	{"accrcolor1.b",  0},	
	{"accrcolor2.r",  0},	
	{"accrcolor2.g",  0},	
	{"accrcolor2.b",  0},	
	{"vertrows",      1},	
	{"horicols",      1},	
	{"vertpoints1",   1},	
	{"horipoints1",   1},	
	{"vertpoints2",   1},	
	{"horipoints2",   1},	
	{"vertpoints3",   1},	
	{"horipoints3",   1},	
	{"vertpoints4",   1},	
	{"horipoints4",   1},	
	{"vertpoints5",   1},	
	{"horipoints5",   1},	
	{"vertpoints6",   1},	
	{"horipoints6",   1},	
	{"vertpoints7",   1},	
	{"horipoints7",   1},	
	{"vertpoints8",   1},	
	{"horipoints8",   1},	
	{"vertpoints9",   1},	
	{"horipoints9",   1},	
	{"vertpoints10",  1},	
	{"horipoints10",  1},	
	{"vertpoints11",  1},	
	{"horipoints11",  1},	
	{"vertpoints12",  1},	
	{"horipoints12",  1},	
	{"vertpoints13",  1},	
	{"horipoints13",  1},	
	{"vertpoints14",  1},	
	{"horipoints14",  1},	
	{"vertpoints15",  1},	
	{"horipoints15",  1},	
	{"vertpoints16",  1},	
	{"horipoints16",  1},	
	{"vertpoints17",  1},	
	{"horipoints17",  1},	
	{"vertpoints18",  1},	
	{"horipoints18",  1},	
	{"vertpoints19",  1},	
	{"horipoints19",  1},	
	{"vertpoints20",  1},	
	{"horipoints20",  1}
};

CLASSPROPERTY tm_cszCurve[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"curvetype",    2 },	
	{"xdigits",      2 },	
	{"ydigits",      2 },	
	{"cols",         2 },	
	{"rows",         2 },	
	{"curvename",    12},	
	{"curvenameID",  11},	
	{"xname",        12},	
	{"yname",        12},	
	{"xnameID",      11},	
	{"ynameID",      11},	
	{"xmin",         8 },	
	{"xmax",         8 },	
	{"ymin",         8 },	
	{"ymax",         8 },	
	{"xstart",       8 },	
	{"xend",         8 },	
	{"ystart",       8 },	
	{"yend",         8 },	
	{"xunit",        8 },	
	{"yunit",        8 },	
	{"linecolor0",   4 },	
	{"linename0",   12},	
	{"linenameID0",  11},	
	{"linetype0",  2 },	
	{"linecolor1",  4 },	
	{"linename1",  12},	
	{"linenameID1",  11},	
	{"linetype1",  2 },	
	{"linecolor2",  4 },	
	{"linename2",  12},	
	{"linenameID2",  11},	
	{"linetype2",  2 },	
	{"linecolor3",  4 },	
	{"linename3",  12},	
	{"linenameID3",  11},	
	{"linetype3",  2 },	
	{"linecolor4",  4 },	
	{"linename4",  12},	
	{"linenameID4",  11},	
	{"linetype4",  2 },	
	{"linecolor5",  4 },	
	{"linename5",  12},	
	{"linenameID5",  11},	
	{"linetype5",  2 },	
	{"linecolor6",  4 },	
	{"linename6",  12},	
	{"linenameID6",  11},	
	{"linetype6",  2 },	
	{"linecolor7",  4 },	
	{"linename7",  12},	
	{"linenameID7",  11},	
	{"linetype7",  2 },	
	{"linecolor8",  4 },	
	{"linename8",  12},	
	{"linenameID8",  11},	
	{"linetype8",  2 },	
	{"linecolor9",  4 },	
	{"linename9",  12},	
	{"linenameID9",  11},	
	{"linetype9",  2 }

};

CLASSPROPERTY tm_cszCurveEx[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"doublebuffer", 14},
	{"curvetype",    2 },
	{"xdigits",      2 },
	{"ydigits",      2 },
	{"cols",         2 },
	{"rows",         2 },
	{"curvename",    11},
	{"curvenameID",  11},
	{"xname",        12},	
	{"yname",        12},	
	{"xnameID",      11},	
	{"ynameID",      11},	
	{"xmin",         8 },	
	{"xmax",         8 },	
	{"ymin",         8 },	
	{"ymax",         8 },	
	{"ymin2",        8 },	
	{"ymax2",        8 },	
	{"xstart",       8 },	
	{"xend",         8 },	
	{"ystart",       8 },	
	{"yend",         8 },	
	{"xunit",        8 },	
	{"yunit",        8 },	
	{"xnameshow",    14},	
	{"ynameshow",    14},	
	{"xarrowshow",   14},	
	{"yarrowshow",   14},	
	{"xaxestype",    2 },	
	{"yaxestype",    2 },	
	{"xscaletype",   2 },	
	{"yscaletype",   2 },	
	{"titletype",    2 },	
	{"cutlinetype",  2 },	
	{"xgridcolor",   2 },	
	{"ygridcolor",   2 },	
	{"xaxescolor",   2 },	
	{"yaxescolor",   2 },	
	{"reference",    2 },	
	{"yrulecolor",   2 },	
	{"xrulecolor",   2 },	
	{"xmove",        2 },	
	{"ymove",        2 },	
	{"prompt",       12},	
	{"promptID",     11},	
	{"linecolor0",   4 },	
	{"linename0",    12},	
	{"linenameID0",  11},	
	{"linetype0",    2 },	
	{"linecolor1",   4 },	
	{"linename1",    12},	
	{"linenameID1",  11},	
	{"linetype1",    2 },	
	{"linecolor2",   4 },	
	{"linename2",    12},	
	{"linenameID2",  11},	
	{"linetype2",    2 },	
	{"linecolor3",   4 },	
	{"linename3",    12},	
	{"linenameID3",  11},	
	{"linetype3",    2 },	
	{"linecolor4",   4 },	
	{"linename4",    12},	
	{"linenameID4",  11},	
	{"linetype4",    2 },	
	{"linecolor5",   4 },	
	{"linename5",    12},	
	{"linenameID5",  11},	
	{"linetype5",    2 },	
	{"linecolor6",   4 },	
	{"linename6",    12},	
	{"linenameID6",  11},	
	{"linetype6",    2 },	
	{"linecolor7",   4 },	
	{"linename7",    12},	
	{"linenameID7",  11},	
	{"linetype7",    2 },	
	{"linecolor8",   4 },	
	{"linename8",    12},	
	{"linenameID8",  11},	
	{"linetype8",    2 },	
	{"linecolor9",   4 },	
	{"linename9",    12},	
	{"linenameID9",  11},	
	{"linetype9",    2 }	

};

CLASSPROPERTY 	tm_cszValueStr[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"value0",    11},
	{"value1",    11},
	{"value2",    11},
	{"value3",    11},
	{"value4",    11},
	{"value5",    11},
	{"value6",    11},
	{"value7",    11},
	{"value8",    11},
	{"value9",    11},
	{"value10",   11},
	{"value11",   11},
	{"value12",   11},
	{"value13",   11},
	{"value14",   11},
	{"value15",   11},
	{"value16",   11},
	{"value17",   11},
	{"value18",   11},
	{"value19",   11},
	{"value20",   11},
	{"value21",   11},
	{"value22",   11},
	{"value23",   11},
	{"value24",   11},
	{"value25",   11},
	{"value26",   11},
	{"value27",   11},
	{"value28",   11},
	{"value29",   11},
	{"value30",   11},
	{"value31",   11},
	{"value32",   11},
	{"value33",   11},
	{"value34",   11},
	{"value35",   11},
	{"value36",   11},
	{"value37",   11},
	{"value38",   11},
	{"value39",   11},
	{"value40",   11},
	{"value41",   11},
	{"value42",   11},
	{"value43",   11},
	{"value44",   11},
	{"value45",   11},
	{"value46",   11},
	{"value47",   11},
	{"value48",   11},
	{"value49",   11},
	{"value50",   11},
	{"value51",   11},
	{"value52",   11},
	{"value53",   11},
	{"value54",   11},
	{"value55",   11},
	{"value56",   11},
	{"value57",   11},
	{"value58",   11},
	{"value59",   11},
	{"value60",   11},
	{"value61",   11},
	{"value62",   11},
	{"value63",   11},
	{"value64",   11},
	{"value65",   11},
	{"value66",   11},
	{"value67",   11},
	{"value68",   11},
	{"value69",   11},
	{"value70",   11},
	{"value71",   11},
	{"value72",   11},
	{"value73",   11},
	{"value74",   11},
	{"value75",   11},
	{"value76",   11},
	{"value77",   11},
	{"value78",   11},
	{"value79",   11},
	{"value80",   11},
	{"value81",   11},
	{"value82",   11},
	{"value83",   11},
	{"value84",   11},
	{"value85",   11},
	{"value86",   11},
	{"value87",   11},
	{"value88",   11},
	{"value89",   11},
	{"value90",   11},
	{"value91",   11},
	{"value92",   11},
	{"value93",   11},
	{"value94",   11},
	{"value95",   11},
	{"value96",   11},
	{"value97",   11},
	{"value98",   11},
	{"value99",   11},
	{"value100",  11},
	{"value101",  11},
	{"value102",  11},
	{"value103",  11},
	{"value104",  11},
	{"value105",  11},
	{"value106",  11},
	{"value107",  11},
	{"value108",  11},
	{"value109",  11},
	{"value110",  11},
	{"value111",  11},
	{"value112",  11},
	{"value113",  11},
	{"value114",  11},
	{"value115",  11},
	{"value116",  11},
	{"value117",  11},
	{"value118",  11},
	{"value119",  11},
	{"value120",  11},
	{"value121",  11},
	{"value122",  11},
	{"value123",  11},
	{"value124",  11},
	{"value125",  11},
	{"value126",  11},
	{"value127",  11},
	{"value128",  11},
	{"value129",  11},
	{"value130",  11},
	{"value131",  11},
	{"value132",  11},
	{"value133",  11},
	{"value134",  11},
	{"value135",  11},
	{"value136",  11},
	{"value137",  11},
	{"value138",  11},
	{"value139",  11},
	{"value140",  11},
	{"value141",  11},
	{"value142",  11},
	{"value143",  11},
	{"value144",  11},
	{"value145",  11},
	{"value146",  11},
	{"value147",  11},
	{"value148",  11},
	{"value149",  11},
	{"value150",  11},
	{"value151",  11},
	{"value152",  11},
	{"value153",  11},
	{"value154",  11},
	{"value155",  11},
	{"value156",  11},
	{"value157",  11},
	{"value158",  11},
	{"value159",  11},
	{"value160",  11},
	{"value161",  11},
	{"value162",  11},
	{"value163",  11},
	{"value164",  11},
	{"value165",  11},
	{"value166",  11},
	{"value167",  11},
	{"value168",  11},
	{"value169",  11},
	{"value170",  11},
	{"value171",  11},
	{"value172",  11},
	{"value173",  11},
	{"value174",  11},
	{"value175",  11},
	{"value176",  11},
	{"value177",  11},
	{"value178",  11},
	{"value179",  11},
	{"value180",  11},
	{"value181",  11},
	{"value182",  11},
	{"value183",  11},
	{"value184",  11},
	{"value185",  11},
	{"value186",  11},
	{"value187",  11},
	{"value188",  11},
	{"value189",  11},
	{"value190",  11},
	{"value191",  11},
	{"value192",  11},
	{"value193",  11},
	{"value194",  11},
	{"value195",  11},
	{"value196",  11},
	{"value197",  11},
	{"value198",  11},
	{"value199",  11},
	{"value200",  11},
	{"value201",  11},
	{"value202",  11},
	{"value203",  11},
	{"value204",  11},
	{"value205",  11},
	{"value206",  11},
	{"value207",  11},
	{"value208",  11},
	{"value209",  11},
	{"value210",  11},
	{"value211",  11},
	{"value212",  11},
	{"value213",  11},
	{"value214",  11},
	{"value215",  11},
	{"value216",  11},
	{"value217",  11},
	{"value218",  11},
	{"value219",  11},
	{"value220",  11},
	{"value221",  11},
	{"value222",  11},
	{"value223",  11},
	{"value224",  11},
	{"value225",  11},
	{"value226",  11},
	{"value227",  11},
	{"value228",  11},
	{"value229",  11},
	{"value230",  11},
	{"value231",  11},
	{"value232",  11},
	{"value233",  11},
	{"value234",  11},
	{"value235",  11},
	{"value236",  11},
	{"value237",  11},
	{"value238",  11},
	{"value239",  11},
	{"value240",  11},
	{"value241",  11},
	{"value242",  11},
	{"value243",  11},
	{"value244",  11},
	{"value245",  11},
	{"value246",  11},
	{"value247",  11},
	{"value248",  11},
	{"value249",  11},
	{"value250",  11},
	{"value251",  11},
	{"value252",  11},
	{"value253",  11},
	{"value254",  11},
	{"value255",  11},
	{"default",   11}
};

CLASSPROPERTY	tm_cszCheckBox[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"text",						tmSTR},
	{"textID",						tmSTR},
	{"prompt",						tmSTR},
	{"promptID",					tmSTR},
	{"checked",						tmBOOL}
};

CLASSPROPERTY	tm_cszProgressbar[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"dbid0",						tmSTR},
	{"maxid",						tmSTR},
	{"minid",						tmSTR},
	{"value",						tmINT64},
	{"min",							tmINT64},
	{"max",							tmINT64},
	{"position",					tmWORD},
	{"dblimit",						tmBOOL},
	{"bartype",						tmWORD}
};

CLASSPROPERTY	tm_cszMemo[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"focuscolor",					tmWORD},
	{"startstrindex",				tmWORD},
	{"foucusindex",					tmWORD},
	{"foucusstrIndex",				tmWORD},
	{"bar",							tmBOOL},
	{"str0",						tmUSTR},
	{"strID0",						tmSTR},
	{"str1",						tmUSTR},
	{"strID1",						tmSTR},
	{"str2",						tmUSTR},
	{"strID2",						tmSTR},
	{"str3",						tmUSTR},
	{"strID3",						tmSTR},
	{"str4",						tmUSTR},
	{"strID4",						tmSTR},
	{"str5",						tmUSTR},
	{"strID5",						tmSTR},
	{"str6",						tmUSTR},
	{"strID6",						tmSTR},
	{"str7",						tmUSTR},
	{"strID7",						tmSTR},
	{"str8",						tmUSTR},
	{"strID8",						tmSTR},
	{"str9",						tmUSTR},
	{"strID9",						tmSTR},
	{"str10",						tmUSTR},
	{"strID10",						tmSTR},
	{"str11",						tmUSTR},
	{"strID11",						tmSTR},
	{"str12",						tmUSTR},
	{"strID12",						tmSTR},
	{"str13",						tmUSTR},
	{"strID13",						tmSTR},
	{"str14",						tmUSTR},
	{"strID14",						tmSTR},
	{"str15",						tmUSTR},
	{"strID15",						tmSTR},
	{"str16",						tmUSTR},
	{"strID16",						tmSTR},
	{"str17",						tmUSTR},
	{"strID17",						tmSTR},
	{"str18",						tmUSTR},
	{"strID18",						tmSTR},
	{"str19",						tmUSTR},
	{"strID19",						tmSTR}
};

CLASSPROPERTY	tm_cszScrollBar[] =
{
	{"privilege", 					tmINT},  
	{"left",						tmSHORT},
	{"top",							tmSHORT},
	{"right",						tmSHORT},
	{"bottom",						tmSHORT},
	{"wtype",						tmWORD},
	{"taborder",					tmINT},
	{"fgc",							tmDWORD},
	{"bgc",							tmDWORD},
	{"title",						tmUSTR},
	{"titleID",						tmSTR},
	{"fontsize",					tmINT},
	{"titlewidth",					tmINT}, 
	{"titleheight",					tmINT},
	{"leftcontrol",					tmSTR},
	{"rightcontrol",				tmSTR},
	{"upcontrol",					tmSTR},
	{"downcontrol",					tmSTR},
	{"visible",						tmBOOL},
	{"enabled",						tmBOOL},
	{"extag",						tmINT},
	{"colorcontrol",				tmINT},
	{"colorchange",					tmINT},
	{"destcolor",					tmWORD},
	{"bordercolor",					tmWORD},
	{"aiop",						tmINT},
	{"aiwnd",						tmSTR},
	{"aiid",						tmSTR},
	{"aivalue",						tmINT64},
	{"aidvalue",					tmINT64},
	{"aisvalue",					tmINT64},
	{"aimsgid",						tmINT},
	{"ailparam",					tmINT},
	{"aiwparam",					tmINT},
	{"aivalue0",					tmINT64},
	{"aivalue1",					tmINT64},
	{"aivalue2",					tmINT64},
	{"aivalue3",					tmINT64},
	{"aivalue4",					tmINT64},
	{"aivalue5",					tmINT64},
	{"aivalue6",					tmINT64},
	{"aivalue7",					tmINT64},
	{"aivalue8",					tmINT64},
	{"aivalue9",					tmINT64},
	{"barrange",					tmWORD},
	{"barposition",					tmWORD},
	{"bartype",						tmWORD}
};

char*	u_cszClassName[] = {
	"CtmWnd",
	"CtmEdit",
	"CtmEditX1",
	"CtmEditX2",
	"CtmSelectEdit",
	"CtmSelectBox",
	"CtmSelectBit",
	"CtmStaticX2",
	"CtmButton",
	"CtmToolButton",
	"CtmImageBox",
	"CtmToolBar",
	"CtmPromptBar",
	"CtmStatusBar",
	"CtmMainFrame",
	"CtmView",
	"CtmFormView",
	"CtmDialog",
	"CtmWndSplash",
	"CtmCartoon",
	"CtmValueInt",
	"CtmLineTable",
	"CCurve",
	"CtmCurveEx",
	"CtmValueStr",
	"CtmCheckBox",
	"CtmProgressBar",
	"CtmMemo",
	"CtmScrollBar"
	};
	
void		SetPropertyListValue()
{
	tm_ClassList.pszClassName = u_cszClassName;
	tm_ClassList.pszClassProperty[0] 	= tm_cszWnd;
	tm_ClassList.dwPropertyCount[0] 	= sizeof(tm_cszWnd)/sizeof(CLASSPROPERTY);
	tm_ClassList.pszClassProperty[1] 	= tm_cszEdit;
	tm_ClassList.dwPropertyCount[1]		= sizeof(tm_cszEdit)/sizeof(CLASSPROPERTY);
	tm_ClassList.pszClassProperty[2] 	= tm_cszEditX1;   
	tm_ClassList.dwPropertyCount[2] 	= sizeof(tm_cszEditX1)/sizeof(CLASSPROPERTY);    
	tm_ClassList.pszClassProperty[3] 	= tm_cszEditX2;   
	tm_ClassList.dwPropertyCount[3] 	= sizeof(tm_cszEditX2)/sizeof(CLASSPROPERTY);    
	tm_ClassList.pszClassProperty[4] 	= tm_cszSelectEdit; 
	tm_ClassList.dwPropertyCount[4] 	= sizeof(tm_cszSelectEdit)/sizeof(CLASSPROPERTY); 
	tm_ClassList.pszClassProperty[5] 	= tm_cszSelectBox; 
	tm_ClassList.dwPropertyCount[5] 	= sizeof(tm_cszSelectBox)/sizeof(CLASSPROPERTY);   
	tm_ClassList.pszClassProperty[6] 	= tm_cszSelectBit; 
	tm_ClassList.dwPropertyCount[6] 	= sizeof(tm_cszSelectBit)/sizeof(CLASSPROPERTY);   
	tm_ClassList.pszClassProperty[7] 	= tm_cszStaticX2;  
	tm_ClassList.dwPropertyCount[7] 	= sizeof(tm_cszStaticX2)/sizeof(CLASSPROPERTY);   
	tm_ClassList.pszClassProperty[8] 	= tm_cszButton;
	tm_ClassList.dwPropertyCount[8] 	= sizeof(tm_cszButton)/sizeof(CLASSPROPERTY);
	tm_ClassList.pszClassProperty[9] 	= tm_cszToolButton; 
	tm_ClassList.dwPropertyCount[9] 	= sizeof(tm_cszToolButton)/sizeof(CLASSPROPERTY);  
	tm_ClassList.pszClassProperty[10] 	= tm_cszImageBox; 
	tm_ClassList.dwPropertyCount[10] 	= sizeof(tm_cszImageBox)/sizeof(CLASSPROPERTY);    
	tm_ClassList.pszClassProperty[11] 	= tm_cszToolBar;   
	tm_ClassList.dwPropertyCount[11] 	= sizeof(tm_cszToolBar)/sizeof(CLASSPROPERTY);   
	tm_ClassList.pszClassProperty[12] 	= tm_cszPromptBar; 
	tm_ClassList.dwPropertyCount[12] 	= sizeof(tm_cszPromptBar)/sizeof(CLASSPROPERTY);   
	tm_ClassList.pszClassProperty[13] 	= tm_cszStatusBar; 
	tm_ClassList.dwPropertyCount[13] 	= sizeof(tm_cszStatusBar)/sizeof(CLASSPROPERTY);   
	tm_ClassList.pszClassProperty[14] 	= tm_cszMainFrame; 
	tm_ClassList.dwPropertyCount[14] 	= sizeof(tm_cszMainFrame)/sizeof(CLASSPROPERTY);   
	tm_ClassList.pszClassProperty[15] 	= tm_cszView;   
	tm_ClassList.dwPropertyCount[15] 	= sizeof(tm_cszView)/sizeof(CLASSPROPERTY);      
	tm_ClassList.pszClassProperty[16] 	= tm_cszFormView;
	tm_ClassList.dwPropertyCount[16] 	= sizeof(tm_cszFormView)/sizeof(CLASSPROPERTY);
	tm_ClassList.pszClassProperty[17] 	= tm_cszDialog;
	tm_ClassList.dwPropertyCount[17] 	= sizeof(tm_cszDialog)/sizeof(CLASSPROPERTY);
	tm_ClassList.pszClassProperty[18] 	= tm_cszWndSplash;
	tm_ClassList.dwPropertyCount[18] 	= sizeof(tm_cszWndSplash)/sizeof(CLASSPROPERTY);
	tm_ClassList.pszClassProperty[19] 	= tm_cszCartoon; 
	tm_ClassList.dwPropertyCount[19] 	= sizeof(tm_cszCartoon)/sizeof(CLASSPROPERTY);
	tm_ClassList.pszClassProperty[20] 	= tm_cszValueInt;
	tm_ClassList.dwPropertyCount[20] 	= sizeof(tm_cszValueInt)/sizeof(CLASSPROPERTY);
	tm_ClassList.pszClassProperty[21] 	= tm_cszLineTable;
	tm_ClassList.dwPropertyCount[21] 	= sizeof(tm_cszLineTable)/sizeof(CLASSPROPERTY);
	tm_ClassList.pszClassProperty[22] 	= tm_cszCurve;
	tm_ClassList.dwPropertyCount[22] 	= sizeof(tm_cszCurve)/sizeof(CLASSPROPERTY);
	tm_ClassList.pszClassProperty[23] 	= tm_cszCurveEx;
	tm_ClassList.dwPropertyCount[23] 	= sizeof(tm_cszCurveEx)/sizeof(CLASSPROPERTY);
	tm_ClassList.pszClassProperty[24] 	= tm_cszValueStr;
	tm_ClassList.dwPropertyCount[24] 	= sizeof(tm_cszValueStr)/sizeof(CLASSPROPERTY);
	tm_ClassList.pszClassProperty[25] 	= tm_cszCheckBox;
	tm_ClassList.dwPropertyCount[25] 	= sizeof(tm_cszCheckBox)/sizeof(CLASSPROPERTY);
	tm_ClassList.pszClassProperty[26] 	= tm_cszProgressbar;
	tm_ClassList.dwPropertyCount[26] 	= sizeof(tm_cszProgressbar)/sizeof(CLASSPROPERTY);
	tm_ClassList.pszClassProperty[27] 	= tm_cszMemo;
	tm_ClassList.dwPropertyCount[27] 	= sizeof(tm_cszMemo)/sizeof(CLASSPROPERTY);
	tm_ClassList.pszClassProperty[28] 	= tm_cszScrollBar;
	tm_ClassList.dwPropertyCount[28] 	= sizeof(tm_cszScrollBar)/sizeof(CLASSPROPERTY);
		
}
